export enum Dil {
  TR = 1
}

export enum Durum {
  PASIF = 0, AKTIF = 1, MANTIKSAL_SILINMIS = 2
}

export enum DurumAktifPasif {
  AKTIF = 1, PASIF = 0
}

export enum EvetHayir {
  EVET = 1, HAYIR = 0
}

export enum DosyaYonu {
  LEHE = 1, ALEYHE = 2
}

export enum DosyaTipi {
  ICRA = 1, DAVA = 2, DEGISIK_IS = 3, KLASOR = 4
}

export enum SablonDokumTipi {
  NONE = "NONE", ICRA = "ICRA", DAVA = "DAVA", DOSYA_GRUBU = "DOSYA_GRUBU"
}

export enum DosyaTipiIcraDava {
  ICRA = 1, DAVA = 2
}

export enum VeriTipi {
  STRING = 1, SAYI = 2, REFERANS_TABLOSU = 3, EVET_HAYIR = 4, TARIH = 5, ONDALIK_SAYI = 6, SAAT = 7, PARA = 8, YUZDE = 9
}

export enum HareketKaynagi {
  HOPE = 1, UYAP = 2
}

export enum BolgeIller {
  ADANA = 1,
  ANKARA = 6,
  ANTALYA = 7,
  AYDIN = 9,
  BURSA = 16,
  DENIZLI = 20,
  DIYARBAKIR = 21,
  EDIRNE = 22,
  ERZURUM = 25,
  ESKISEHIR = 26,
  GAZIANTEP = 27,
  ISTANBUL = 34,
  IZMIR = 35,
  KAYSERI = 38,
  KONYA = 42,
  MALATYA = 44,
  MANISA = 45,
  ORDU = 52,
  SAKARYA = 54,
  SAMSUN = 55,
  SIVAS = 58,
  TRABZON = 61,
  VAN = 65,
  ZONGULDAK = 67,
  KIRIKKALE = 71
}

export enum AsamaGrubu {
  SISTEM_ASAMASI = 1,
  ICRA_ASAMASI = 2,
  BORCLU_ASAMASI = 3,
  MAL_ASAMASI = 4,
  DAVA_ASAMASI = 5,
  MERCI_ASAMASI = 6,
  TALIMAT_ASAMASI = 8,
  DEGISIK_IS_ASAMASI = 9,
  DOKUM_ASAMASI = 10,
  ARAMA_ASAMASI = 11,
  DURUM_ASAMASI = 12,
  TEMINAT_ASAMASI = 13
}

export enum GorusSahibi {
  HUKUK_YONETIMI_GORUSU = 1,
  VEKIL_GORUSU = 2
}

export enum ErisilenUygulama {
  DOSYA_GORUNTULEME = 1,
  HARICI_SISTEM_BORC_SORGULAMA = 2,
  DAVA_GORUNTULEME = 3,
  DEGISIK_IS_GORUNTULEME = 4,
  DAS_SORGULAMA = 5,
  DAS_GORUNTULEME = 6,
  KLASOR_GORUNTULEME = 7
}

export enum RaporFormat {
  PDF = 0,
  DOCX = 1,
  XLS = 3,
  XLSX = 4,
  XLSY = 5,
  UDF = 6
}

export enum DosyaYuklemeTipi {
  HDA_ICRA_DOSYA_LISTESI = 42,
  HDA_DAVA_DOSYA_LISTESI = 43,
  HDA_ICRA_TUTAR_LISTESI = 44,
  HDA_DAVA_TUTAR_LISTESI = 45,
  HDA_BELGE_LISTESI = 47,
  HDA_TOPLU_EK_BILGI_TIPI_EKLEME = 53,
  HDA_TOPLU_DAVA_TURU_ALT_TURU_EKLEME = 54,
  HDA_TOPLU_ICRA_EK_BILGI_TIPI_EKLEME = 55,

}

export enum AdresYukleme {
  HDA_ADRES_LISTESI = 48
}

export enum MalYuklemeTipi {
  HDA_MAL_LISTESI = 52
}

export enum KgfRapor {
  KGF_TAHSILAT_RAPORU = 1,
  KGF_MVU_RAPORU = 2,
}

export enum DosyaGrupTipi {
  KULLANICI_TANIMLI = 1,
  ICRA_ACIS = 2,
  MASRAF_EKLEME = 3,
  TOPLU_DOKUM = 4,
  UYAP_XML = 5,
  ICRA_YENILEME = 6,
  TOPLU_DAVA_ACMA = 7,
  DAVA_KULLANICI_TANIMLI = 8,
  HACIZ_PLANLAMA = 9,
  IS_ATAMA = 10,
  DAVA_IS_ATAMA = 11,
  ICRA_MUDURLUGUNE_DEVIR = 12,
  KVKK_IMHA_ICRA = 13,
  KVKK_IMHA_DAVA = 14
}

export enum BilgiNotuTipi {
  ODEME_SOZU = 1,
  BORCLU_BULUNAMADI = 2,
  BORCLU_OLMUS = 3,
  YENIDEN_ARAMA = 4,
  DIGER = 5,
  YUZYUZE_GORUSME = 6,
  TELEFONLA_ARAMA = 7,
  HARICEN_YUKLEME = 8,
  ICRA_TALEBI = 12,
  ONEMLI_NOT = 22,
  ITIRAZ = 21,
  SIRKET_NOTU = 25
}

export enum BireyselKurumsal {
  BIREYSEL = 1,
  KURUMSAL = 2
}

export enum EtkiAnaliziTipi {
  BTK = 1,
  TOPLU_DUSUM = 2
}

export enum DavaTipi {
  ADLI_HUKUK = 1,
  ADLI_CEZA = 2,
  IDARI_IDARE = 3,
  IDARI_VERGI = 4,
  TUKETICI_SIKAYETI = 5,
  SIGORTA_TAHKIM_KOMISYONU = 6
}

export enum SorunTipi {
  HITAM_OLAMAMA = 1,
  BORDRO_URETEMEME = 2,
  DOSYA_OLUSTURMA = 3,
  DOSYA_ASAMA_GECIS_SURESI = 4,
  BORCLU_ASAMA_GECIS_SURESI = 5,
  MERCI_ASAMA_GECIS_SURESI = 6,
  SISTEM_ASAMA_GECIS_SURESI = 7,
  MAL_ASAMA_GECIS_SURESI = 8,
  DOSYA_TAKIP = 9,
  DAVA_HITAM_OLAMAMA = 10,
  DOSYA_UYARI = 11,
  UYAP = 12,
  IDARI_TAKIP = 13
}

export enum SorunAltTipi {
  BAKIYESI_KALMAMIS_DEGIL = 1,
  BORDRO_URETEMEME = 2,
  COGRAFI_BIRIM_TANIMLI_DEGIL = 3,
  DOSYA_ASAMA_GECIS_SURESI = 4,
  BORCLU_ASAMA_GECIS_SURESI = 5,
  MERCI_ASAMA_GECIS_SURESI = 6,
  SISTEM_ASAMA_GECIS_SURESI = 7,
  MAL_ASAMA_GECIS_SURESI = 8,
  ICRA_BAKIYESI_BULUNUYOR = 9,
  KAPATILMAMIS_MASRAF_VAR = 10,
  MALLAR_SATIS_HAZIRLIK_VEYA_HACIZ_KONULDU_DURUMUNDA = 11,
  HARICI_TAHSIL_HARCI_DOSYA_KAPAMA_MASRAFI_GIRILMEMIS = 12,
  BAGLI_DAVALAR_SONUCLANDIRILMAMIS = 13,
  BAGLI_DAVALARDA_ONAYLANMAMIS_VEKALET_UCRETI_BULUNUYOR = 14,
  MUTABAKATLAR_TAMAMLANMAMIS = 15,
  DAVA_DURUSMA_SONUCU_ZAMANINDA_GIRILMEMIS = 16,
  DOSYA_KILITLI = 17,
  TEMINAT_VERILDI_DURUMUNDA_TEMINATI_BULUNDU = 18,
  DAVA_DOSYASI_HITAM_DURUMDA = 19,
  DAVAYA_BAGLI_ICRALAR_HITAM_OLMAMIS = 20,
  DAVA_BAKIYESI_BULUNUYOR = 21,
  DAVA_MASRAFLAR_ACIK = 22,
  DAVA_TEMINAT_VERILDI_DURUMDA_TEMINAT_VAR = 23,
  DAVA_ONAY_TALEBI_YAPILMAMIS_VU_VAR = 24,
  ARA_KARAR_SONUCU_ZAMANINDA_GIRILMEMIS = 25,
  TERKIN_DOSYA_UYARISI = 26,
  BORCLU_AD_SOYAD_BILGILERI_EKSIK = 27,
  BORCLU_ADRES_BILGISI_EKSIK = 28,
  MERCI_DOSYA_NO_EKSIK = 29,
  ICRA_AC_TAR_UYAP_AC_TAR_ILERI = 30,
  DOSYA_KAPAMA_UYAP_DOSYA_KAPAMA_BEKLENEN = 31,
  DOSYA_KAPAMA_UYAP_HTH_MASRAFI_BEKLENEN = 32,
  IKAZ_MEKTUBU_YOK = 33,
  IKAZ_MEKTUBU_TEBLIG_TARIHINE_ULASILAMIYOR = 34
}

export enum ZorlukDerecesi {
  KOLAY = 1,
  ORTA = 2,
  ZOR = 3
}

export enum KapatmaNedeni {
  CEVAP_BEKLENIYOR = 1,
  COZUMLENDI = 2,
  HATALI_GOREV_FISI = 3,
  MUKERRER = 4
}

export enum TekitTipi {
  NORMAL = 1,
  PERFORMANS = 2,
  YENI_EVRAK = 3
}

export enum EvrakAsama {
  VERI_GIRISI_BEKLENIYOR = 1,
  VERI_GIRISI_TAMAMLANDI = 2,
  ISLEME_ALINDI = 3,
  BEKLEMEDE = 4,
  KAPANDI = 5
}

export enum EvrakTuru {
  DAVA_MAHKEME = 1,
  DIGER = 2,
  HACIZ_IHBARNAMESI = 3,
  ICRA = 4,
  IHTARNAME = 5,
  SAVCILIK = 6
}

export enum BorcYonu {
  LEH = 1,
  ALEYH = 2
}

export enum MahkemeTuru {
  ASLIYE_HUKUK_MAHKEMESI = 1,
  SULH_HUKUK_MAHKEMESI = 2,
  ICRA_CEZA_MAHKEMESI = 3,
  ASLIYE_CEZA_MAHKEMESI = 4,
  SULH_CEZA_MAHKEMESI = 5,
  AGIR_CEZA_MAHKEMESI = 6,
  ICRA_TETKIK_MERCII = 7,
  IS_MAHKEMESI = 8,
  ASLIYE_TICARET_MAHKEMESI = 9,
  IDARE_MAHKEMESI = 10,
  VERGI_MAHKEMESI = 11,
  TUKETICI_MAHKEMESI = 12,
  DANISTAY = 13,
  FIKRI_VE_SINAI_HAKLAR_HUK_MAK = 14,
  FIKRI_VE_SINAI_HAKLAR_CEZ_MAK = 15,
  DENIZ_TICARET_MAHKEMESI = 16,
  COCUK_MAHKEMESI = 17,
  KADASTRO_MAHKEMESI = 18,
  AILE_MAHKEMESI = 19,
  CUMHURIYET_BAS_SAVCILIGI = 20,
  YARGITAY_HUKUK_DAIRESI = 21,
  ICRA_HUKUK_MAHKEMESI = 22,
  INFAZ_HAKIMLIGI = 24,
  BOLGE_IDARE_MAHKEMESI = 25,
  COCUK_AGIR_CEZA_MAHKEMESI = 28,
  ICRA_MAHKEMESI = 29,
  DENIZCILIK_IHTISAS_MAHKEMESI = 30,
  TRAFIK_MAHKEMESI = 31,
  YARGITAY_CEZA_DAIRESI = 32,
  TUKETICI_HAKEM_HEYETI = 33,
  SIGORTA_TAHKIM_KOMISYONU = 34,
  BOLGE_ADLIYE_MAHKEMESI_CEZA_DAIRESI = 35,
  BOLGE_ADLIYE_MAHKEMESI_HUKUK_DAIRESI = 36,
  ARABULUCULUK_BUROSU = 37
}

export enum CografiBirimTipi {
  ULKE = 1,
  IL = 2,
  ILCE = 3
}

export enum FaizOraniPeriyodu {
  YIL = 1,
  AY = 2,
  GUN = 3
}

export enum VekaletUcretiTarifeTipi {
  ICRA_TARIFESI = 1,
  DAVA_TARIFESI = 2,
  MVU_TARIFESI = 3,
  MAKTU_TARIFESI = 4,
  K2B3M = 29,
  K2B5M = 30,
  K2B7M = 31,
  K2B8M = 32,
  K2B9M = 33,
  K2B18Ma = 34
}

export enum DavaUcretTipi {
  NISBI = 1,
  MAKTU = 2
}

export enum VekaletUcretiEsasDeger {
  ESAS_ALACAK = 1,
  ICRA_TAKIP_CIKIS_DEGERI = 2,
}

export enum GrupTipi {
  TCKN = "TCKN",
  VKN = "VKN",
  AD_SOYAD = "BORCLU_AD_SOYAD",
}

export class Constants {
  static readonly TURKIYE = 100000;
  static readonly DATE_FMT = 'dd.MM.yyyy';
  static readonly DATE_TIME_FMT = `${Constants.DATE_FMT} HH:mm:ss`;
  static readonly PARA_FMT = '1.2-2';
  static readonly paraBirimiList = [
    {icon: 'fa fa-turkish-lira-sign', value: '949', label: 'TRY'},
    {icon: 'fa fa-dollar-sign', value: '840', label: 'USD'},
    {icon: 'fa fa-euro-sign', value: '978', label: 'EUR'},
    {icon: '', value: '960', label: 'SDR'},
    {icon: '', value: '36', label: 'AUD'},
    {icon: '', value: '214', label: 'DKK'},
    {icon: 'fa fa-pound-sign', value: '826', label: 'GBP'},
    {icon: '', value: '756', label: 'CHF'},
    {icon: '', value: '752', label: 'SEK'},
    {icon: '', value: '124', label: 'CAD'},
    {icon: '', value: '414', label: 'KWD'},
    {icon: '', value: '578', label: 'NOK'},
    {icon: '', value: '682', label: 'SAR'},
    {icon: 'fa fa-yen-sign', value: '392', label: 'JPY'},
    {icon: '', value: '975', label: 'BGN'},
    {icon: '', value: '946', label: 'RON'},
    {icon: 'fa fa-ruble-sign', value: '643', label: 'RUB'},
    {icon: '', value: '364', label: 'IRR'},
    {icon: 'fa fa-yen-sign', value: '156', label: 'CNY'},
    {icon: '', value: '586', label: 'PKR'},
    {icon: 'fa fa-coins', value: '479', label: 'GR'},
  ];
  static readonly LAZY_DATATABLE_EXCEL_REPORT_WARNING_LIMIT = 30000;
  static readonly LAZY_DATATABLE_EXCEL_PIECED_REPORT_WARNING_LIMIT = 5000;
}

export enum KisiTipi {
  HISSEDAR = 1,
  KEFIL = 2,
  DAVALI = 3,
  DAVACI = 4,
  BORCLU = 5,
  SIRKET_YETKILISI = 6,
  VARIS = 7,
  ALACAKLI = 8,
  KARSI_TARAF = 9,
  IHBAR_EDILEN = 10,
  BILGI_NITELIGINDE = 11,
  SUPHELI_SANIK = 12,
  MUSTEKI = 13,
  MAGDUR = 14,
  SIKAYETCI = 15,
  SIKAYET_EDILEN = 16,
  DAVALI_YANINDA_KATILAN = 17,
  DAVACI_YANINDA_KATILAN = 18,
  TANIK = 19,
  YENI_MALIK = 20,
  KARSI_DAVALI = 21,
  KARSI_DAVACI = 22,
  FAILI_MECHUL = 23,
  BILGISI_EKSIK = 24,
  ARABULUCU = 25,
  MAGDUR_YANINDA_KATILAN = 26,
  SIKAYETCI_YANINDA_KATILAN = 27,
  TARAF_OLMAYAN_MUSTERI = 28,
  SUPHELI = 29,
  SANIK = 30,
  DAVACI_KARSI_DAVALI = 31,
  DAVALI_KARSI_DAVACI = 32,
  BIRLESEN_DOSYA_DAVALISI = 33,
  BIRLESEN_DOSYA_DAVACISI = 34,
  ASLI_MUDAHIL = 35,
  FERI_MUDAHIL = 36,
  KATILAN_MUDAHIL = 37,
  MUDAFI = 38,
  ITIRAZ_EDEN = 39,
  TALEP_EDEN = 40
}

export enum MasrafKapamaTalepOnayDurumu {
  GIRIS_YAPILIYOR = 501,
  VEKIL_ONAYI_BEKLIYOR = 502,
  HUKUK_ONAYI_BEKLIYOR = 503,
  FINANS_ONAYI_BEKLIYOR = 504,
  FINANSA_GONDERILMEYI_BEKLIYOR = 505,
  FINANSA_ILETILDI = 506,
  HESABA_YATTI = 507,
  REDDEDILDI = 508,
  FINANSA_GONDERILMEYECEK = 509,
  ON_KAYIT_FINANS_ILETILDI = 510,
  ON_KAYIT_KESINLESTI = 511,
  EKSIK_HATALI_BELGE = 512,
  UST_VEKIL_ONAYI_BEKLENIYOR = 513,
  ONAY_SURECI_BASLADI = 2001
}

export enum AvansTalepOnayDurumu {
  AVANS_GIRIS_YAPILIYOR = 101,
  AVANS_VEKIL_ONAYI_BEKLIYOR = 102,
  AVANS_HUKUK_ONAYI_BEKLIYOR = 103,
  AVANS_FINANS_ONAYI_BEKLIYOR = 112,
  AVANS_UST_VEKIL_ONAYI_BEKLIYOR = 113,
  AVANS_ONAY_SURECI_BASLADI = 114,
  AVANS_MUHASEBE_GOND_BEKLIYOR = 104,
  AVANS_MUHASEBEYE_ILETILDI = 105,
  AVANS_HESABA_YATTI = 106,
  AVANS_REDDEDILDI = 107,
  AVANS_ODENMEYECEK = 108,
  CEVAP_BEKLENIYOR = 109
}

export enum AvansNakitIadeTalepOnayDurumu {
  AVANS_IADE_TALEP_YAPILDI = 3412,
  AVANS_IADE_TALEP_ONAYLANDI = 3413,
  AVANS_IADE_TALEP_REDDEDILDI = 3414,
  AVANS_IADE_TALEP_IPTAL_EDILDI = 3415
}

export enum AvansNakitIadeTalepDetayOnayDurumu {
  HUKUK_ONAYI_BEKLIYOR = 3607,
  REDDEDILDI = 3608,
  IPTAL_EDILDI = 3613,
  TEBISE_ILETILMEYI_BEKLIYOR = 3609,
  TEBISE_ILETILDI = 3610,
  HESAPTAN_CEKILDI = 3611,
  HESAPTAN_CEKILEMEDI = 3612
}

export enum KonfigurasyonParametreleriDetayOnayDurumu {
  HUKUK_ONAYI_BEKLIYOR = 3707,
  HUKUK_REDDEDILDI = 3708,
  HUKUK_ONAYLANDI = 3709
}

export enum KonfigurasyonParametreleriOnayDurumu {
  KONFIGURASYON_PARAMETRELERI_TALEP_ONAYLANDI = 3416,
  KONFIGURASYON_PARAMETRELERI_TALEP_REDDEDILDI = 3417,
  KONFIGURASYON_PARAMETRELERI_TALEP_YAPILDI = 3418
}

export enum MktVekilOneriDurum {
  HUKUK_ONAYLADI = 504,
  SILINDI = 507,
  ONAY_VEKILE_ODENMEZ = 508
}

export enum FaizIndirimTaksitIslemTuru {
  DOSYA = 1,
  URUN = 2,
  NONE = 0
}

export enum BankaIslemTuru {
  DOSYA = 1,
  URUN = 2,
}

export enum IslemTipi {
  DOSYA_BAZLI = 1,
  URUN_BAZLI = 2,
}

export enum BorcDusumEtkiDurumu {
  ONAYA_TABI_DUSUM_YAPILABILIR = 1,
  DUSUM_YAPILABILIR = 2,
  DUSUM_YAPILAMAZ = 3,
  OTOMATIK_DUSUM_ONAYA_TABI = 4,
  OTOMATIK_DUSUM_ONAYA_TABI_DEGIL = 5
}

export enum TaksitlendirmeIslemi {
  TAKSIT_SAYISI = 0,
  TAKSIT_TUTARI = 1
}

export enum FaizIndirimTaksitDurumu {
  DEVAM_EDIYOR = 1,
  IHLAL_EDILDI = 2,
  IPTAL_EDILDI = 3,
  ONAY_BEKLIYOR = 4,
  REDDEDILDI = 5
}

export enum BorcDusumTalepDetayOnayDurumu {
  BORC_DUSUM_TALEBI_FINANS_ONAYI_BEKLIYOR = 1705,
  BORC_DUSUM_TALEBI_REDDEDILDI_FINANS = 1706,
  BORC_DUSUM_TALEBI_HUKUK_ONAYI_BEKLIYOR = 1704,
  BORC_DUSUM_TALEBI_REDDEDILDI_HUKUK = 1703,
  BORC_DUSUM_TALEBI_ONAYLANDI = 1702,
  BORC_DUSUM_TALEBI_YAPILDI = 1701
}

export enum TutarDuzeltmeTalepDetayOnayDurumu {
  TUTAR_DUZELTME_TALEBI_ONAY_BEKLIYOR = 1713,
  TUTAR_DUZELTME_TALEBI_HUKUK_ONAYLANDI = 1714,
  TUTAR_DUZELTME_TALEBI_HUKUK_REDDEDILDI = 1715
}

export enum ItirazIncelemeTalepDetayOnayDurumu {
  IIT_TALEP_YAPILDI = 1716,
  IIT_TALEP_ONAYLANDI = 1717,
  IIT_TALEP_REDDEDILDI = 1718
}

export enum IndirimTalepDosyaOnayDurumu {
  INDIRIM_TALEBI_ONAY_BEKLIYOR = 1719,
  INDIRIM_TALEBI_HUKUK_ONAYLANDI = 1720,
  INDIRIM_TALEBI_HUKUK_REDDEDILDI = 1721,
}

export enum TahsilatGirisTalepDetayOnayDurumu {
  TGT_TALEP_YAPILDI = 1707,
  TGT_TALEP_ONAYLANDI = 1708,
  TGT_TALEP_REDDEDILDI = 1709,
  TAHSILAT_GIRIS_TALEBI_HUKUK_ONAYI_BEKLIYOR = 2207,
  TAHSILAT_GIRIS_TALEBI_FINANSA_GONDERILMEYI_BEKLIYOR = 2208,
  TAHSILAT_GIRIS_TALEBI_FINANSA_ILETILDI = 2209,
  TAHSILAT_GIRIS_TALEBI_PARA_ODENDI = 2210,
  TAHSILAT_GIRIS_TALEBI_ONAY_IPTAL_EDILDI = 2211,
  TAHSILAT_GIRIS_TALEBI_ODEME_IPTAL_EDILDI = 2212,
  TAHSILAT_GIRIS_TALEBI_IPTAL_EDILDI = 2213,
}

export enum BelgeYuklemeTalepDetayOnayDurumu {
  BELGE_TALEP_ONAY_BEKLIYOR = 301,
  BELGE_TALEP_ONAYLANDI = 302,
  BELGE_TALEP_REDDEDILDI = 303
}

export enum FazlaOdemeTalepDetayOnayDurumu {
  E_DEVLET_FAZLA_ODEME_IADE_TALEP_ALINDI = 2201,
  E_DEVLET_FAZLA_ODEME_IADE_TALEP_BANKAYA_ILETILDI = 2202,
  E_DEVLET_FAZLA_ODEME_IADE_TALEP_SAP_ILETILDI = 2203,
  E_DEVLET_FAZLA_ODEME_IADE_TALEP_ODENDI = 2204,
  E_DEVLET_FAZLA_ODEME_IADE_TALEP_ODENMEDI = 2205,
  E_DEVLET_FAZLA_ODEME_IADE_TALEP_IPTAL_EDILDI = 2206
}

export enum BelgeCekmeTalepDetayOnayDurumu {
  BELGE_CEKME_TALEBI_YAPILDI = 2001,
  BELGE_CEKME_TALEBI_ONAY = 2002,
  BELGE_CEKME_TALEBI_RED = 2003
}

export enum DavaMvuOdemeTalepDetayOnayDurumu {
  DAVA_MVU_ODEME_TALEP_UST_VEKIL_ONAY_BEKLIYOR = 3701,
  DAVA_MVU_ODEME_TALEP_HUKUK_ONAY_BEKLIYOR = 3702,
  DAVA_MVU_ODEME_TALEP_SMM_DAHIL_OLMAYI_BEKLIYOR = 3703,
  DAVA_MVU_ODEME_TALEP_REDDEDILDI = 3704,
  DAVA_MVU_ODEME_TALEP_IPTAL_EDILDI = 3705,
  DAVA_MVU_ODEME_SMM_DAHIL_OLDU = 3706
}

export enum DavaEmsalTalepDetayOnayDurumu {
  DAVA_EMSAL_TALEBI_YAPILDI = 1501,
  DAVA_EMSAL_TALEBI_ONAYLANDI = 1502,
  DAVA_EMSAL_TALEBI_REDDEDILDI = 1503
}

export enum DavaHitamTalepDetayOnayDurumu {
  DAVA_HITAM_YAP_TALEP_YAPILDI = 1731,
  DAVA_HITAM_YAP_TALEP_ONAY = 1732,
  DAVA_HITAM_YAP_TALEP_RED = 1733
}

export enum TemyizeGitmemeTalepDetayOnayDurumu {
  TEMYIZE_GITMEME_TALEP_YAPILDI = 1725,
  TEMYIZE_GITMEME_TALEP_ONAY = 1726,
  TEMYIZE_GITMEME_TALEP_RED = 1727
}

export enum DavaVekaletUcretiOnayTalepDetayOnayDurumu {
  DAVA_VEKALET_ONAY_TALEP_BEKLIYOR = 1001,
  DAVA_VEKALET_REDDEDILDI = 1002,
  DAVA_VEKALET_ONAYLANDI = 1003,
  DAVA_VEKALET_VEKILE_ODENMEZ = 1004
}

export enum VekilTalimatTalepDetayOnayDurumu {
  VEKIL_TALIMAT_TALEBI_YAPILDI = 1401,
  VEKIL_TALIMAT_TALEBI_ONAYLANDI = 1402,
  VEKIL_TALIMAT_TALEBI_REDDEDILDI = 1403
}

export enum DavaMvuOdemeTalepIslemKodu {
  DAVA_MVU_ODEME_TALEP_YAPILDI = 1290,
  DAVA_MVU_ODEME_TALEP_UST_VEKIL_ONAYI = 1291,
  DAVA_MVU_ODEME_TALEP_HUKUK_ONAY = 1292,
  DAVA_MVU_ODEME_TALEP_RED = 1293,
  DAVA_MVU_ODEME_TALEP_SMM_DAHIL_EDILDI = 1299,
  DAVA_MVU_ODEME_TALEP_IPTAL = 1300
}

export enum MasrafKapamaOnayIslemKodu {
  MASRAF_KAPAMA_VEKIL_ONAY = 648,
  MASRAF_KAPAMA_VEKIL_RED = 649,
  MASRAF_KAPAMA_HUKUK_ONAY = 650,
  MASRAF_KAPAMA_HUKUK_RED = 655,
  MASRAF_KAPAMA_FINANS_ONAY = 651,
  MASRAF_KAPAMA_FINANS_RED = 656
}

export enum KullaniciIslemTalepOnayDurumu {
  KULLANICI_ISLEM_TALEP_YAPILDI = 1901,
  KULLANICI_ISLEM_TALEP_REDDEDILDI = 1903,
  KULLANICI_ISLEM_TALEP_ONAYLANDI = 1902,
  KULLANICI_EKLEME_TALEBI_IPTAL_EDILDI = 1904
}

export enum KullaniciIslemTalepIslemKodu {
  KULLANICI_ISLEM_TALEP_KULLANICI_EKLEME = 1254,
  KULLANICI_ISLEM_TALEP_KULLANICI_GUNCELLEME = 1255,
  KULLANICI_ISLEM_TALEP_KULLANICI_SILME = 1256,
  KULLANICI_ISLEM_TALEP_KULLANICI_ROL_GUNCELLEME = 1257,
  KULLANICI_ISLEM_TALEP_KULLANOICI_GRUBU_GUNCELLEME = 1276
}

export enum SistemParametreTalepOnayDurumu {
  HUKUK_ONAYI_BEKLIYOR = 3401,
  ONAYLANDI = 3402,
  REDDEDILDI = 3403
}

export enum SistemParametreTalepIslemKodu {
  SISTEM_PARAMETRE_TALEP_GIRIS = 1258,
  SISTEM_PARAMETRE_TALEP_ONAY = 1259,
  SISTEM_PARAMETRE_TALEP_RED = 1260
}

export enum TeminatVermeTalepOnayDurumu {
  HUKUK_ONAYI_BEKLIYOR = 2004,
  TEMINAT_VERME_TALEP_ONAYLANDI = 2005,
  TEMINAT_VERME_TALEP_REDDEDILDI = 2006,
  FINANS_ONAYI_BEKLIYOR = 2007,
  FINANSA_GONDERILMEYI_BEKLIYOR = 2008,
  TEMINAT_VERME_TALEBI_BANKA_YAZISI_BEKLENIYOR = 2018,
  TEMINAT_VERME_TALEBI_IPTAL_EDILDI = 2019,
  TEMINAT_VERME_TALEBI_TEMINAT_BILGILERI_GIRISI_BEKLENIYOR = 2020,
  TEMINAT_VERME_TALEBI_TEMINAT_BILGILERI_TAMAMLANDI = 2021,
  TEMINAT_VERME_TALEBI_ILK_GIRIS = 2022,
  TEMINAT_VERME_TALEP_AVANS_SURECI_BEKLENIYOR = 2023,
  TEMINAT_VERME_TALEP_TEBISE_ILETILDI = 2024,
  TEMINAT_VERME_TALEP_UST_VEKIL_ONAYI_BEKLIYOR = 2025
}

export enum FaizIndirimTaksitTalepOnayDurumu {
  FAIZ_INDIRIM_TAKSIT_TALEP_UST_VEKIL_ONAY_BEKLIYOR = 3501,
  FAIZ_INDIRIM_TAKSIT_TALEP_HUKUK_ONAY_BEKLIYOR = 3502,
  FAIZ_INDIRIM_TAKSIT_TALEP_ONAYLANDI = 3503,
  FAIZ_INDIRIM_TAKSIT_TALEP_REDDEDILDI = 3504,
  FAIZ_INDIRIM_TAKSIT_TALEP_IPTAL_EDILDI = 3505,
  FAIZ_INDIRIM_TAKSIT_TALEP_TEBISE_ILETILDI = 3506,
  FAIZ_INDIRIM_TAKSIT_TALEP_TEBISE_ILETILMEYI_BEKLIYOR = 3507
}

export enum BankaBorcDusumTalepOnayDurumu {
  BANKA_BORC_DUSUM_TALEBI_YAPILDI = 1734,
  BANKA_BORC_DUSUM_TALEBI_ONAYLANDI = 1735,
  BANKA_BORC_DUSUM_TALEBI_REDDEDILDI_HUKUK = 1736,
  BANKA_BORC_DUSUM_TALEBI_HUKUK_ONAYI_BEKLIYOR = 1737,
  BANKA_BORC_DUSUM_TALEBI_UST_VEKIL_ONAYI_BEKLIYOR = 1740,
  BANKA_BORC_DUSUM_TALEBI_REDDEDILDI_UST_VEKIL = 1741,
  BANKA_BORC_DUSUM_TALEBI_REDDEDILDI = 1742,
  BANKA_BORC_DUSUM_TALEBI_IPTAL_EDILDI = 1743,
  BANKA_BORC_DUSUM_TALEBI_ONAY_SURECINDE = 1744,
  BANKA_BORC_DUSUM_TALEBI_VAZGECILDI = 1745
}

export enum TeminatVermeTalepIslemKodu {
  TEMINAT_TALEP_ONAY = 1204,
  TEMINAT_TALEP_RED = 1203,
  TEMINAT_TALEP_HUKUK_ONAY = 1207,
  TEMINAT_VERME_TALEP_FINANS_ONAY = 1208,
  TEMINAT_VERME_TALEP_FINANS_ILETILDI = 1209,
  TEMINAT_VERME_TALEP_GIRIS = 1268,
  TEMINAT_VERME_TALEP_VEKIL_ONAY = 1269,
  TEMINAT_VERME_TALEP_IPTAL = 1270,
  TEMINAT_VERME_TALEP_TEMINAT_BILGILERI_TAMAMLANDI_YAP = 1271,
  TEMINAT_VERME_TALEP_GUNCELLEME_ISLEMI = 1272,
  TEMINAT_VERME_TALEP_YAZISI_GONDERME = 1273,
  TEMINAT_VERME_TALEP_TEMINAT_BILGILERI_GIRME = 1274,
  TEMINAT_VERME_TALEP_BANKA_BILGILERI_GUNCELLEME = 1275,
  TEMINAT_VERME_TALEP_AVANS_SURECI_BASARILI = 1264,
  TEMINAT_VERME_TALEP_AVANS_SURECI_BASARISIZ = 1265,
  TEMINAT_VERME_TALEP_UST_VEKIL_ONAYI = 1308
}

export enum KtvuFeragatTalepDetayOnayDurumu {
  KTVU_FERAGAT_TALEP_UST_VEKIL_ONAYI_BEKLIYOR = 3601,
  KTVU_FERAGAT_TALEP_ONAYLANDI = 3602,
  KTVU_FERAGAT_TALEP_REDDEDILDI = 3603
}

export enum SatisaIstirakTalepDetayOnayDurumu {
  SATISA_ISTIRAK_TALEBI_YAPILDI = 2101,
  SATISA_ISTIRAK_TALEBI_ONAY = 2102,
  SATISA_ISTIRAK_TALEBI_RED = 2103
}

export enum MukerrerTakipBaslatmakIcinTakipIptalTalepDetayOnayDurumu {
  MUKERRER_ICRA_ACMA_TALEBI_YAPILDI = 1301,
  MUKERRER_ICRA_ACMA_TALEBI_ONAYLANDI = 1302,
  MUKERRER_ICRA_ACMA_TALEBI__REDDEDILDI = 1303
}

export enum DosyaIadeTalepDetayOnayDurumu {
  DOSYA_IADE_TALEP_EDILDI = 401,
  DOSYA_IADE_ONAYLANDI = 402,
  DOSYA_IADE_REDDEDILDI = 403,
  UST_VEKIL_ONAYI_BEKLIYOR = 3825,
  HUKUK_ONAYI_BEKLIYOR = 3826,
  DOSYA_IADE_TALEBI_IPTAL_EDILDI = 3827,
}

export enum DosyaDusurmeTalepDetayOnayDurumu {
  DOSYA_DUSURME_ONAY_BEKLIYOR = 201,
  DOSYA_DUSURME_ONAYLANDI = 202,
  DOSYA_DUSURME_REDDEDILDI = 203
}

export enum TmddenCikarmaTalepDetayOnayDurumu {
  TMDDEN_CIKARMA_ONAY_BEKLIYOR = 801,
  TMDDEN_CIKARMA_ONAYLANDI = 802,
  TMDDEN_CIKARMA_REDDEDILDI = 803,
}

export enum IcradanParaYattiTalepDetayOnayDurumu {
  PARA_YATTI_ILK_GIRIS = 601,
  PARA_YATTI_PARA_CEKILDI = 602,
  PARA_YATTI_DOSYA_BULUNAMADI = 603,
  PARA_YATTI_PARA_YOK = 604,
  PARA_YATTI_PARA_CEKILIYOR = 605
}

export enum FinansOnayTalepDetayOnayDurumu {
  FINANS_ONAY_TALEP_YAPILDI = 1722,
  FINANS_ONAY_TALEP_ONAYLANDI = 1723,
  FINANS_ONAY_TALEP_REDDEDILDI = 1724
}

export enum DosyaAtamaTalepDetayOnayDurumu {
  DOSYA_ATAMA_TALEBI_YAPILDI = 1201,
  DOSYA_ATANDI = 1202,
  DOSYA_ATAMA_TALEBI_REDDEDILDI = 1203
}

export enum MutalaaTalepOnayDurumu {
  MUTALAA_TALEBI_1_SEVIYE_ONAY_BEKLIYOR = 1801,
  MUTALAA_TALEBI_ONAYLANDI = 1802,
  MUTALAA_TALEBI_REDDEDILDI = 1803,
  MUTALAA_TALEBI_2_SEVIYE_ONAY_BEKLIYOR = 1804,
  MUTALAA_TALEBI_1_SEVIYE_KAPAMA_ONAY_BEKLIYOR = 1805,
  MUTALAA_TALEBI_2_SEVIYE_KAPAMA_ONAY_BEKLIYOR = 1806,
  MUTALAA_TALEBI_BEKLEMEYE_AL = 1807,
  MUTALAA_TALEBI_VEKILE_ATAMA_BEKLIYOR = 1808,
  MUTALAA_TALEBI_VEKIL_GORUSU_BEKLENIYOR = 1809,
  MUTALAA_TALEBI_VEKIL_UYGUN_GORDU = 1810,
  MUTALAA_TALEBI_VEKIL_REDDETTI = 1811,
  MUTALAA_TALEBI_2_SEVIYE_VEKIL_GORUSU_BEKLENIYOR = 1812
}


export enum KararDuzeltmeyeGitmeTalepDetayOnayDurumu {
  KARAR_DUZELT_GITME_TALEP_YAPILDI = 1728,
  KARAR_DUZELTMEYE_GITME_TALEP_ONAY = 1729,
  KARAR_DUZELTMEYE_GITME_TALEP_RED = 1730
}

export enum AleyheOdemeTalepDetayOnayDurumu {
  ALEYHE_ODEME_TALEP_ILK_GIRIS = 1101,
  ALEYHE_ODEME_FIN_GOND_BEKLIYOR = 1110,
  ALEYHE_ODEME_FIN_GONDERILDI = 1104,
  ALEYHE_ODEME_TALEP_ONAYLANDI = 1112,
  ALEYHE_ODEME_TALEP_PARA_ODENDI = 1102,
  ALEYHE_ODEME_TALEP_ONAYI_IPTAL_EDILDI = 1114,
  ALEYHE_ODEME_TALEP_ODEME_IPTAL_EDILDI = 1113,
  ALEYHE_ODEME_TALEP_TW_ONAY_BEKLIYOR = 1115,
  ALEYHE_ODEME_TALEP_IPTAL_EDILDI = 1111,

  ALEYHE_ICRA_REDDEDILDI = 1103,
  ALEYHE_ICRA_HUKUK_ONAYI = 1105,
  ALEYHE_ICRA_TALEP_KAPANDI = 1106,
  ALEYHE_ICRA_MUTEMET_ONAYI_BEKLIYOR = 1107,
  CEVAP_ONAYLI_ISLENDI = 1108,
  CEVAP_ONAYLI_ISLENEMEDI = 1109


}

export enum TahsilatIptalTalepDetayOnayDurumu {
  TIT_TALEP_YAPILDI = 1710,
  TIT_TALEP_ONAYLANDI = 1711,
  TIT_TALEP_REDDEDILDI = 1712,
}

export enum TeminatIadeTalepDetayOnayDurumu {
  TEMINAT_IADE_TALEP_TALEP_YAPILDI = 2014,
  TEMINAT_IADE_TALEP_TALEP_ONAYLANDI = 2015,
  TEMINAT_IADE_TALEP_TALEP_REDDEDILDI = 2016,
  TEMINAT_IADE_TALEP_FINANS_GONDERILMEYI_BEKLIYOR = 2017,
  TEMINAT_IADE_TALEP_HESAPTAN_CEKILEMEDI = 3605,
  TEMINAT_IADE_TALEP_TEBISE_ILETILDI = 3606
}

export enum MasrafKapamaOnayHukukIslemKodu {
  MASRAF_KAPAMA_VEKIL_ONAY = 648,
  MASRAF_KAPAMA_HUKUK_ONAY = 650
}

export enum AsamaEnums {
  ARANMADI = 83,
  ARANDI = 84,
  ARANMAYACAK = 85,
  ULASILAMADI = 86,
  YENIDEN_ARANACAK = 87,
  ODEME_EMRI_GONDERILMEYI_BEKLIYOR = 21,
  BA_ODEME_EMRI_CEVABI_BEKLIYOR = 22,
  BA_BILA_TEBLIG = 23,
  BILA_TEBLIG_VEFAT = 24,
  BA_BORCLU_BULUNAMADI = 27,
  TEBLIGATLI = 28,
  ITIRAZIN_IPTALI_DAVASI_ACILMASI_BEKLIYOR = 29,
  ITIRAZIN_IPTALI_DAVASININ_SONUCLANMASI_BEKLENIYOR = 30,
  ITIRAZ_KABUL_EDILDI = 31,
  BA_ACIZ = 36,
  BA_TAKIP_KESINLESTI = 63,
  MURACAAT_BEKLIYOR = 49,
  YARGILAMA_DEVAM_EDIYOR = 50,
  DURUSMA_GUNUNU_BEKLIYOR = 51,
  KARAR_GEREKCELI = 52,
  TEMYIZ_SONUCU_BEKLIYOR = 53,
  TEMYIZ_SONUCLANDI = 54,
  KARAR_DUZELTME_SONUCLANDI = 55,
  KARAR_DUZELTME = 56,
  KESINLESTI = 57,
  DA_ITIRAZ_SONUCU_BEKLIYOR = 78,
  KARAR = 79,
  ON_INCELEME_BEKLIYOR = 88,
  ON_INCELEME_GUNU_BEKLIYOR = 89,
  SAVCILIK_HAZIRLIK_SORUSTURMASI_BEKLIYOR = 97,
  SAVCILIK_HAZIRLIK_SORUSTURMASI_SONUCLANDI = 98,
  TAKIPSIZLIGE_ITIRAZ_SONUCU_BEKLIYOR = 99,
  TAKIPSIZLIGE_ITIRAZ_SONUCLANDI = 100,
  CEVAP_BEKLIYOR = 93,
  KARAR_BEKLIYOR = 94,
  KARAR_TUH_HAK = 95,
  GOREVLI_MAHKEME_BILGILERI_BEKLENIYOR = 104,
  YETKILI_MAHKEME_BILGILERI_BEKLENIYOR = 105,
  YARGILAMAYA_ARA_VERILDI = 106,
  GOREVSIZLIK_TEMYIZ_SONUCU_BEKLIYOR = 117,
  ISTINAF_SONUCU_BEKLENIYOR = 126,
  ISTINAF_SONUCLANDI = 127,
  TEFRIK_SONUCU_MAHKEME_BILGILERI_BEKLENIYOR = 134,
  DI_MURACAAT_BEKLIYOR = 75,
  RAPOR_TEDBIR_BEKLIYOR = 76,
  RAPOR_KARAR_GELDI = 77,
  ITIRAZ_SONUCU_BEKLIYOR = 101,
  ITIRAZ_EDILDI = 96,
  DOKUM_HAZIRLANDI = 80,
  DOKUM_GONDERILDI = 81,
  DOKUM_CEVABI_GELDI = 82,
  DERDEST = 90,
  BAKIYESI_KALMAMIS = 91,
  HITAM = 92,
  NPL_SATIS = 130,
  ICRA_ACILMAYI_BEKLIYOR = 9,
  ICRA_GUNU_BEKLIYOR = 10,
  ODEME_EMRI_CEVABI_BEKLIYOR = 11,
  BORCLU_BULUNAMADI = 12,
  BORCLU_BULUNAMADI_VEFAT_SAHTE_KIMLIK = 13,
  ODEME_EMRI_TEBLIG_EDILDI = 14,
  TAKIP_KESINLESTI = 15,
  ACIZ = 16,
  HACIZ = 17,
  SATIS = 18,
  BELIRSIZ = 58,
  TESPIT_EDILDI = 39,
  HAC_MUZ_CEV_BEKLIYOR = 40,
  HACIZ_KONULAMAZ = 41,
  SATIS_HAZIRLIK = 42,
  KAYIT_KONULDU = 43,
  HACIZ_KALDIRILDI = 44,
  KIYMET_TAKDIRI_YAPILDI = 45,
  SATIS_KARARI_BEKLIYOR = 46,
  SATIS_GUNUNU_BEKLIYOR = 47,
  SATILDI = 48,
  HACIZ_KONUSUZ_KALDI = 103,
  SATILAMADI = 113,
  TESCIL_BEKLIYOR = 114,
  TAHLIYE_BEKLIYOR = 115,
  TAHLIYE_EDILDI = 116,
  KIYMET_TAKDIRI_KESINLESTI = 118,
  BILA_TEBLIG = 107,
  MA_BELIRSIZ = 64,
  TAKIPTE = 65,
  TAKIPTEN_DUSMUS = 66,
  TAKIPTEN_DUSMUS_YENILEME_BASLATILDI = 67,
  ATAMA_BEKLIYOR = 1,
  TMD = 2,
  ASKIDA = 3,
  VEKILDE = 4, LIMITALTI = 8, GIRISI_TAMAMLANDI = 59, BILGILERI_EKSIK = 60, IDARI_TAKIPTE = 102, HUKUK_ONCESI = 125, ON_IDARI_TAKIP = 145,
  ISLEME_ALINMAYI_BEKLIYOR = 71, ISLEME_ALINDI = 72, REDDEDILDI = 73, ISLEM_TAMAMLANDI = 74,
  ILK_GIRIS = 119,
  TESLIM_ETME_TALEBI_ONAYDA = 128,
  IADE_ALMA_TALEBI_ONAYDA = 129,
  ODEME_CEVABI_ISLENDI = 120,
  TEMINAT_VERILDI = 109,
  IADE_ALINDI = 110,
  IRAT_KAYDEDILDI = 111,
  NAKDE_DONUSTURULDU = 112,
  GOREVSIZLIK_ISTINAF_SONUCU_BEKLENIYOR = 135,
  GOREVSIZLIK_ISTINAF_SONUCLANDI = 136,
  MTS = 137
}

export enum AramaAsamasi {
  ARANMADI = 83,
  ARANDI = 84,
  ARANMAYACAK = 85,
  ULASILAMADI = 86,
  YENIDEN_ARANACAK = 87
}

export enum BorcluAsamasi {
  ODEME_EMRI_GONDERILMEYI_BEKLIYOR = 21,
  BA_ODEME_EMRI_CEVABI_BEKLIYOR = 22,
  BA_BILA_TEBLIG = 23,
  BILA_TEBLIG_VEFAT = 24,
  BA_BORCLU_BULUNAMADI = 27,
  TEBLIGATLI = 28,
  ITIRAZIN_IPTALI_DAVASI_ACILMASI_BEKLIYOR = 29,
  ITIRAZIN_IPTALI_DAVASININ_SONUCLANMASI_BEKLENIYOR = 30,
  ITIRAZ_KABUL_EDILDI = 31,
  BA_ACIZ = 36,
  BA_TAKIP_KESINLESTI = 63
}

export enum DavaAsamasi {
  MURACAAT_BEKLIYOR = 49,
  YARGILAMA_DEVAM_EDIYOR = 50,
  DURUSMA_GUNUNU_BEKLIYOR = 51,
  KARAR_GEREKCELI = 52,
  TEMYIZ_SONUCU_BEKLIYOR = 53,
  TEMYIZ_SONUCLANDI = 54,
  KARAR_DUZELTME_SONUCLANDI = 55,
  KARAR_DUZELTME = 56,
  KESINLESTI = 57,
  DA_ITIRAZ_SONUCU_BEKLIYOR = 78,
  KARAR = 79,
  ON_INCELEME_BEKLIYOR = 88,
  ON_INCELEME_GUNU_BEKLIYOR = 89,
  SAVCILIK_HAZIRLIK_SORUSTURMASI_BEKLIYOR = 97,
  SAVCILIK_HAZIRLIK_SORUSTURMASI_SONUCLANDI = 98,
  TAKIPSIZLIGE_ITIRAZ_SONUCU_BEKLIYOR = 99,
  TAKIPSIZLIGE_ITIRAZ_SONUCLANDI = 100,
  CEVAP_BEKLIYOR = 93,
  KARAR_BEKLIYOR = 94,
  KARAR_TUH_HAK = 95,
  GOREVLI_MAHKEME_BILGILERI_BEKLENIYOR = 104,
  YETKILI_MAHKEME_BILGILERI_BEKLENIYOR = 105,
  YARGILAMAYA_ARA_VERILDI = 106,
  GOREVSIZLIK_TEMYIZ_SONUCU_BEKLIYOR = 117,
  ISTINAF_SONUCU_BEKLENIYOR = 126,
  ISTINAF_SONUCLANDI = 127,
  TEFRIK_SONUCU_MAHKEME_BILGILERI_BEKLENIYOR = 134,
  GOREVSIZLIK_ISTINAF_SONUCU_BEKLENIYOR = 135,
  GOREVSIZLIK_ISTINAF_SONUCLANDI = 136
}

export enum DegisikIsAsamasi {
  DI_MURACAAT_BEKLIYOR = 75,
  RAPOR_TEDBIR_BEKLIYOR = 76,
  RAPOR_KARAR_GELDI = 77,
  ITIRAZ_SONUCU_BEKLIYOR = 101,
  ITIRAZ_EDILDI = 96
}

export enum DegisikIsTipi {
  BILIRKISI_INCELEMESI = 1,
  DELIL_TESPITI = 2,
  IHTIYATI_HACIZ = 3,
  IHTIYATI_TEDBIR = 4,
  TESPIT = 5,
  TEVDII_MAHALLI_TAYINI = 6,
  IDARI_PARA_CEZASINA_ITIRAZ = 7,
  IDARI_YAPTIRIM_KARARINA_ITIRAZ,
  DIGER = 99
}

export enum DokumAsamasi {
  DOKUM_HAZIRLANDI = 80, DOKUM_GONDERILDI = 81, DOKUM_CEVABI_GELDI = 82
}




export enum UyapDosyaDurumu {
  ACIK = 0,
  KAPALI = 1
}

export enum AtanmaTipi {
  BIRINCI_EL = 1, IKINCI_EL = 2
}

export enum AvansTipi {
  ILK_ICRA_ACILIS = 1,
  DIGER = 2,
  BAGIMSIZ_DAVA = 4,
  HTH = 5,
  TEMINAT = 6,
  GAYRIMENKUL_TESCIL_MASRAFI = 7,
  KTVU_VE_YAR_GIDERI_MASRAFI = 8
}

export enum AvansTipiManuel {
  ILK_ICRA_ACILIS = 1,
  DIGER = 2,
  BAGIMSIZ_DAVA = 4,
  TEMINAT = 6,
  GAYRIMENKUL_TESCIL_MASRAFI = 7,
  KTVU_VE_YAR_GIDERI_MASRAFI = 8
}

export enum AvansDurumu {
  ODEME_SURECINDE = 1,
  KAPAMA_TALEP_EDILDI = 2,
  AVANS_KAPANDI = 3
}

export enum TalepOnayDurumu {
  AVANS_HUKUK_ONAYI_BEKLIYOR = 103,
  AVANS_FINANS_ONAYI_BEKLIYOR = 112,
  GIRIS_YAPILIYOR = 501,
  VEKIL_ONAYI_BEKLIYOR = 502,
  HUKUK_ONAYI_BEKLIYOR = 503,
  FINANS_ONAYI_BEKLIYOR = 504,
  FINANSA_GONDERILMEYI_BEKLIYOR = 505,
  FINANSA_ILETILDI = 506,
  HESABA_YATTI = 507,
  REDDEDILDI = 508,
  FINANSA_GONDERILMEYECEK = 509,
  ON_KAYIT_FINANS_ILETILDI = 510,
  ON_KAYIT_KESINLESTI = 511,
  EKSIK_HATALI_BELGE = 512,
  UST_VEKIL_ONAYI_BEKLIYOR = 513,
  TALEP_ONAYLANDI = 514,
  ONAY_SURECI_BASLADI = 2001,
  FATURA_ISLEM_TALEBI_HUKUK_ONAYI_BEKLIYOR = 3818,
  FATURA_ISLEM_TALEBI_KARSI_SIS_GOND_BEKLIYOR = 3819,
  FATURA_ISLEM_TALEBI_KARSI_SIS_GOND_CVP_BEKLNYR = 3820,
  FATURA_ISLEM_TALEBI_ISLEM_BASARILI = 3821,
  FATURA_ISLEM_TALEBI_ISLEM_REDDEDILDI = 3822,
  FATURA_ISLEM_TALEBI_IPTAL_EDILDI = 3823,
  FATURA_ISLEM_TALEBI_REDDEDILDI = 3824,
  VEKIL_TALIMAT_TALEBI_YAPILDI = 1401,
  VEKIL_TALIMAT_TALEBI_ONAYLANDI = 1402,
  VEKIL_TALIMAT_TALEBI_REDDEDILDI = 1403
}

export enum TalepDetayOnayDurumu {
  ILK_GIRIS = 501,
  VEKIL_TALEP_BASLATTI = 502,
  VEKIL_TALEP_ETTI = 503,
  HUKUK_ONAYLADI = 504,
  ODEME_ONAY = 505,
  YETERSIZ_VEYA_EKSIK_BELGE = 506,
  SILINDI = 507,
  ONAY_VEKILE_ODENMEZ = 508,
  VEKIL_BEKLEMEYE_ALDI = 509,
  UST_VEKIL_ONAYLADI = 510,
  ODEME_ONAY_SURECI = 511
}

export enum BelgeTipi {
  FATURA1 = 1,
  SOZLESME = 2,
  SEVK_IRSALIYESI = 3,
  TASIMA_IRSALIYESIA = 5,
  YOLCU_LISTESI = 6,
  GUNLUK_MUSTERI_LISTESI = 7,
  PERAKENDE_SATIS_VESIKASI = 8,
  GIDER_PUSULASI = 9,
  MUSTAHSIL_MAKBUZU = 10,
  SERBEST_MESLEK_MAKBUZU = 11,
  UCRET_BORDROSU = 12,
  TAAHUTNAME = 13,
  KEFALETNAME = 14,
  MAHKEME_ILAMLARI = 15,
  IHBARNAME = 16,
  KARAR_ORNEKLERI = 17,
  VERGI_MAKBUZLARI = 18,
  DIGER = 19,
  BILIRKISI_RAPORU = 21,
  DILEKCE = 22,
  ARA_KARAR = 23,
  BELGE = 24,
  CAGRI_KAGIDI = 25,
  DANISTAY_KARARI = 26,
  DEKONT = 27,
  DELIL_LISTESI = 28,
  DERKENAR = 29,
  DURUSMA_TUTANAGI = 30,
  E_MAIL = 31,
  EMSAL_YARGITAY_KARARI = 32,
  GEREKCELI_KARAR = 33,
  GONDERILEN_EVRAK = 34,
  GORUSME_KAYITLARI = 35,
  GORUSME_TUTANAGI = 36,
  GUVENLIK_SERTIFIKASI = 37,
  HARC_MAKBUZU = 38,
  HUKUKI_MUTALAA = 39,
  ICRA_DOSYASI_KAPAK_HESABI = 40,
  ICRA_EMRI = 41,
  IDDIANAME = 42,
  IHTARNAME = 43,
  INCELEME_RAPORU = 44,
  INCELEME_TUTANAGI = 45,
  KAPAK_HESABI = 46,
  BELGE_TIPI_KARAR = 47,
  KESIF_TUTANAGI = 48,
  KIRA_SOZLESMESI = 49,
  MEHIL_VESIKASI = 50,
  MUHTIRA = 51,
  MURAFAA = 52,
  MUZEKKERE = 53,
  ODEME_EMRI = 54,
  TEBLIGAT = 55,
  TEMINAT_MEKTUBU = 56,
  TEMYIZ_DILEKCESI = 57,
  TENSIP_TUTANAGI = 58,
  TEVZI_FORMU = 59,
  TUTANAK = 60,
  YARGITAY_ILAMI = 61,
  KOMISYON_KARARI = 62,
  MAKAM_ONAYI = 63,
  TUKETICI_HAKEM_HEYETI_KARARI = 64,
  TRAFIK_KAZASI_TESPIT_TUTANAGI = 65,
  OLAY_YERI_TESPIT_TUTANAGI = 66,
  HASAR_TESPIT_TUTANAGI = 67,
  HASAR_KESIF_TUTANAGI = 68,
  SIGORTA_POLICESI = 69,
  VEKIL_VEKALETNAME_ORNEGI = 70,
  VEKIL_AVUKATLIK_SOZLESMESI = 71,
  VEKIL_ISTIFA_IBRANAME = 72,
  VEKIL_KULLANICI_BILGI_FORMU = 73,
  FORM = 74,
  KAMPANYA_TAAHHUTNAMESI = 75,
  BORCLU_MEKTUBU = 76,
  DAVA_DILEKCESI = 77,
  CEVAP_DILEKCESI = 78,
  CEVABA_CEVAP_DILEKCESI = 79,
  KARAR_DUZELTME_DILEKCESI = 82,
  SAVCILIK_SIKAYET_DILEKCESI = 83,
  GUVENLIK_GUCU_TALEBI = 84,
  REDDIYAT = 91,
  KACAK_TUTANAGI = 101,
  DELIL_FOTO = 102,
  DELIL_VIDEO = 103,
  BORC_DOKUMU = 104,
  TUKETIM_EKSTRESI = 105,
  SAYAC_AYAR_RAPORU = 106,
  IKAZ_MEKTUBU = 107,
  BLURLU_DELIL_FOTO = 115,
  HARICI_BELGE = 2045,
  BILIRKISI_RAPORU_MAPFRE = 2059,
  IHTARNAME_MAPFRE = 2058
}

export enum IslemKodu {
  HUKUK_DOSYA_OLUSTUR = 100,
  ORIJINAL_KAYIT = 101,
  ALEYHE_ORIJINAL_KAYIT = 103,
  ALEYHE_ODEME = 110,
  ODEME_BILDIRIM = 111,
  BORC_DUSUM = 114,
  FATURA_KAPAMA_BILDIRIM = 116,
  IADE_BILDIRIM = 118,
  TERKIN = 120,
  VEKALET_UCRETINDEN_DUSUM = 130,
  TUTAR_SIFIRLAMA = 164,
  DOSYA_ATAMA = 200,
  IADE_ALMA = 201,
  LIMITALTI_MEKTUP_KAYDI_URETME = 202,
  LIMITALTI_AKTARIM = 205,
  ASKIYA_ALMA = 206,
  IDARI_TAKIBE_AKTARIM = 207,
  TMD_DURUMUNA_AKTARMA = 208,
  DOSYA_DEVIR_YAP = 209,
  ICRA_ACMA = 210,
  DOSYA_ICRA_DURUMUNA_GECIRME = 212,
  HICBIR_BORCLUYA_TEBLIG_EDILEMEDI = 214,
  TEBLIG_EDILDI = 216,
  DOSYA_TAKIP_KESINLESTIRME = 217,
  HICBIR_MAL_BULUNAMADI = 218,
  HACIZ_DURUMUNA_GECIRME = 220,
  SATIS_DURUMUNA_GECIRME = 222,
  TEBLIG_GONDERME = 228,
  TEBLIG_ALMA = 229,
  TEBLIG_EDILEMEDI_BILATEBLIG = 230,
  TEBLIG_EDILEMEDI_VEFAT = 232,
  ADRES_BULUNAMADI = 234,
  BORCLU_BULUNAMADI = 236,
  BORCLU_BULUNAMADI_VEFAT = 237,
  ADRES_BULUNDU = 238,
  TEBLIG_ETME = 240,
  ITIRAZ_ETME = 244,
  ITIRAZ_DAVASI_ACMA = 246,
  BORCLU_TAKIP_KESINLESTIRME = 248,
  TEBLIG_BILGISI_GIRISI_VE_TAKIP_KESINLESTIRME = 249,
  ACIZ = 260,
  ITIRAZ_SONUCLANDIRMA = 261,
  ITIRAZ_REDDEDILDI = 262,
  ADRES_ARASTIRMA_MUZEKKERESI_GONDERME = 263,
  HACIZ_MUZEKKERESI_GONDERME = 264,
  MANUEL_ASAMA_GECIS = 265,
  HACIZDEN_DUSME = 271,
  HACIZ_KALDIRMA = 273,
  SATIS_TALEBI_YAPMA = 274,
  KIYMET_TAKDIRI_YAPTIRMA = 272,
  MAL_SATILAMADI = 278,
  MAL_SATILDI = 280,
  ICRA_YENILEME = 292,
  ICRA_YENILEME_SONUC = 293,
  ODEME_IPTAL_BILDIRIM = 311,
  DOSYA_ATAMA_IPTAL = 400,
  IADE_ALMA_IPTAL = 401,
  LIMITALTI_AKTARIM_IPTAL = 405,
  ASKIDAN_INDIRME = 406,
  IDARI_TAKIPTEN_CIKARMA = 407,
  TMD_DURUMUNDAN_CIKARMA = 408,
  DOSYA_DEVIR_IPTAL = 409,
  ICRA_ACILIS_IPTAL = 410,
  HICBIR_BORCLUYA_TEBLIG_EDILEMEDI_IPTALI = 414,
  TEBLIG_ETME_IPTALI = 416,
  DOSYA_TAKIP_KESINLESTIRME_IPTALI = 417,
  HICBIR_MAL_BULUNAMADI_IPTALI = 418,
  HACIZ_DURUMU_IPTALI = 420,
  SATIS_DURUMU_IPTALI = 422,
  TEBLIG_GONDERME_IPTALI = 428,
  TEBLIG_ALMA_IPTALI = 429,
  BILATEBLIG_IPTALI = 430,
  VEFAT_GIRME_IPTALI = 432,
  ADRES_BULUNAMADI_IPTALI = 434,
  BORCLU_BULUNAMADI_IPTALI = 436,
  BORCLU_BULUNAMADI_VEFAT_IPTALI = 437,
  ADRES_BULUNDU_IPTALI = 438,
  TEBLIG__IPTALI = 440,
  ITIRAZ_ETME_IPTALI = 444,
  ITIRAZ_DAVASI_ACMA_IPTALI = 446,
  BORCLU_TAKIP_KESINLESTIRME_IPTALI = 448,
  TEBLIG_BILGISI_GIRISI_VE_TAKIP_KESINLESTIRME_IPTALI = 449,
  ACIZ_IPTALI = 460,
  ICRA_YENILEME_IPTALI = 492,
  ICRA_YENILEME_SONUC_IPTALI = 493,
  MASRAF_GERI_AL = 543,
  ILAMLI_HALE_GETIR = 585,
  KAYIT_EKLEME = 600,
  KAYIT_GUNCELLEME = 601,
  KAYIT_SILME = 602,
  MASRAF_KAPAMA_VEKIL_TALEP = 628,
  MASRAF_KAPAMA_VEKIL_ONAY = 648,
  MASRAF_KAPAMA_HUKUK_ONAY = 650,
  MASRAF_KAPAMA_FINANS_ONAY = 651,
  MASRAF_KAPAMA_TALEBI_GUNCELLEME = 537,
  MASRAF_KAPAMA_HUKUK_RED = 655,
  MASRAF_KAPAMA_FINANS_RED = 656,
  FINANSA_ILETILDI = 160,
  DAVA_ACMA = 910,
  ON_INCELEME = 911,
  ARA_KARAR_VERME = 912,
  ON_INCELEME_GUNU_GIRISI = 913,
  TAHKIKAT_BASLATMA = 914,
  KARAR_VERME = 916,
  ERTELEME = 918,
  GEREKCELI_KARAR_VERME = 920,
  TEMYIZ_BASVURUSU = 922,
  TEMYIZ_SONUCU_GIRISI = 924,
  ITIRAZ_BASVURUSU = 925,
  TEMYIZ_SONRASI_DAVA_YENILEME = 926,
  DAVA_ITIRAZ_SONUCLANDIRMA = 927,
  KARAR_DUZELTME_BASVURUSU = 928,
  KARAR_DUZELTME_SONUC_GIRISI = 930,
  KESIF = 933,
  MURAFAA = 934,
  DURUSMA_TARIHI_BELIRLEME = 935,
  MURACAATA_KALMA = 936,
  DAVA_YENILEME = 937,
  CEVAP_VERME = 937,
  YURUTMEYI_DURDURMA_TALEBI = 940,
  SAVCILI_SORUSTURMA_SONUCU_GIRISI = 942,
  TAKIPSIZLIGE_ITIRAZ = 943,
  TAKIPSIZLIGE_ITIRAZ_SONUC_GIRISI = 944,
  TAKIPSIZLIK_ITIRAZI_SONRASI_SORUSTURMA_YENILEME = 945,
  SURE_UZATMA_TALEBI = 946,
  YARGILAMAYA_ARA_VERME = 947,
  YARGILAMAYA_ARA_VERME_SONUC_GIRISI = 948,
  KARAR_KESINLESTIRME = 949,
  ALEYHE_BORC_DUSUM = 1045,
  GOREVLI_MAHKEME_BILGILERI_GIRISI = 1072,
  TEBLIGE_CEVAP_VERME = 1074,
  YETKILI_MAHKEME_BILGILERI_GIRISI = 1073,
  MUDAHALE_TALEBI_YAPMA = 1075,
  ALEYHE_BORC_DUSUM_IPTAL = 1545,
  MAL_HACIZ_DURUMUNA_GECIRME = 1110,
  MAL_SATIS_PLANLAMA = 1118,
  GOREVSIZLIK_TEMYIZ_BASVURUSU = 1123,
  GOREVSIZLIK_TEMYIZ_SONUC_GIRISI = 1124,
  TAKIP_KES_TARIH_GUNCELLEME_DOSYA = 1098,
  TAKIP_KES_TARIH_GUNCELLEME_BORCLU = 1099,
  MAL_HACIZ_KONULAMAZ = 1112,
  MAL_TESCIL_BILGILERI_GIRME = 1121,
  MAL_TAHLIYE_BILGILERI_GIRME = 1122,
  MAL_KIYMET_TAKDIRI_KESINLESTIRME = 1125,
  MAL_TESCIL_HAZIRLIK_YAPMA = 1126,
  MAL_HACIZ_KONUSUZ_KALDI = 1114,
  YETKI_ITIRAZI = 1137,
  BEYAN_DILEKCESI_SUNMA = 1139,
  ISTINAF_BASVURUSU = 1188,
  ISTINAF_DURUSMA_GIRISI = 1189,
  ISTINAF_SONUC_GIRISI = 1190,
  TEFRIK_SONUCU_MAHKEME_BILGILERI_GIRISI = 1238,
  GOREVSIZLIK_ISTINAF_BASVURUSU = 1261,
  GOREVSIZLIK_ISTINAF_DURUSMA_GIRISI = 1262,
  GOREVSIZLIK_ISTINAF_SONUC_GIRISI = 1263,
  TAKIP_SUPURME = 1304,
  BILIRKISI_INCELEMESI = 1316,
  MASRAF_KAPAMA_TALEBI_ONAY_IPTALI = 1631,
  ONAY_IPTALI_SONRASI_OLUSTURULAN_MASRAF_KAPAMA_TALEBI = 1132,
  LIMIT_ALTINA_AKTAR = 1134,
  LIMIT_ALTINDAN_CIKAR = 1135,
  ICRA_MUDURLUGUNE_DEVIR = 1314,
  GIDEN_AVANS = 1874,
  GIDEN_AVANS_IPTAL = 1875,
  TEBLIGAT_CEVAP_GIRIS = 1877,
  VEKILE_GERI_GONDER = 1885,
  AKTIFE_CEK=1882,
  PASIFE_CEK=1883,
  BIRLESMIS_DOSYA_AYIRMA = 1889,
  DOSYA_AYIRMA= 1890,
  DEGISIK_IS_MURACAAT_ETME = 931,
  DEGISIK_IS_SONUCLANDIRMA = 932,
  DEGISIK_IS_ITIRAZ_ETME = 938,
  DEGISIK_IS_ITIRAZ_SONUCLANDIRMA = 939,
}

export enum ParametreTipi {
  AVANS_MASRAF_PARAM = 10,
  BORDRO_PARAM = 20,
  DOS_ATA_OTO_DAG_PARAM = 30,
  ENTEGRASYON_PARAM = 40,
  FINANSAL_PARAM = 50,
  GENEL_PARAM = 60,
  ICRA_SURE_TUTAR_PARAM = 70,
  SMS_EPOSTA_PARAM = 80,
  SIFRE_PAROLA_PARAM = 90,
  DAVA_HITAM_PARAM = 100,
  ICRA_HITAM_PARAM = 110,
  IDARI_TAKIP_PARAM = 120,
  DAVA_PARAM = 130,
  ICRA_PARAM = 140,
  DOSYA_AKTARIM_PARAM = 150,
  SKOR_KART_RAPOR_PARAM = 160,
  UYAP_PARAM = 170
}

export enum OtomatikManuelTipi {
  MANUEL = 1,
  OTOMATIK = 2,
  BIRLESTIRME = 3
}

export enum CalismaTipi {
  KADROLU = 1,
  SOZLESMELI = 2,
  KISMI_ZAMANLI = 3
}

export enum Sirket {
  DEDAS = 100,
  DEPSAS = 101,
  OTOYOL = 300,
  OIB = 301,
  GIIB = 302,
  NOMAYG = 303,
  OTYLDR = 304,
  TT = 500,
  ASSIST = 501,
  MEMORX = 502,
  TTNET = 510,
  VF = 542,
  AVEA = 555,
  TEB = 666,
  MAPFRE = 700,
  INN1 = 900,
  INN2 = 901,
  KMOASY = 216,
  KMOAVR = 212,
  KEO = 232,
  ERG = 312,
  COK = 286
}

export enum YonetimselTalepler {
  MUTALAA_TALEBI = 18,
  YENI_KULLANICI_EKLEME_TALEBI = 29,
  VEKIL_TALIMAT_TALEBI = 14,
  DOSYA_IADE_TALEBI = 4,
  DOSYA_ATAMA_TALEBI = 12,
  SISTEM_PARAMETRE_TALEP = 34,
  KONFIGURASYON_PARAMETRELERI_TALEP = 41
}

export enum FinansalTalepler {
  AVANS_TALEBI = 1,
  MASRAF_KAPAMA_TALEBI = 5,
  PARA_YATTI_TALEBI = 6,
  MASRAF_GERI_ALMA_TALEBI = 9,
  DAVA_VEKALET_UCRETI_ONAYI_TALEBI = 10,
  ALEYHE_ODEME_TALEBI = 11,
  BORC_DUSUM_TALEBI = 17,
  INDIRIM_TALEBI = 24,
  FINANS_UCRET_ONAY_TALEBI = 25,
  TUTAR_DUZELTME_TALEBI = 22,
  TAHSILAT_GIRIS_TALEBI = 20,
  TAHSILAT_IPTAL_TALEBI = 21,
  ALACAK_IADE_TALEBI = 31,
  FAIZ_INDIRIM_TALEP = 35, // userd
  KTVU_FERAGAT_TALEP = 36,
  DAVA_MVU_ODEME_TALEP = 37,
  BANKA_BORC_DUSUM_TALEP = 39,
  AVANS_IADE_TALEP = 40,
  FATURA_ISLEM_TALEP = 38 // userd
}

export enum IcraTalepler {
  DOSYA_DUSURME_TALEBI = 2,
  BELGE_YUKLEME_TALEBI = 3,
  TMD_DURUMUNDAN_CIKARMA_TALEBI = 8,
  MUKERRER_TAKIP_BASLATMA_ICIN_TAKIP_IPTAL_TALEBI = 13,
  DOSYA_ACMA_TALEBI = 16,
  BELGE_CEKME_TALEBI = 19,
  TEMINAT_IADE_TALEBI = 33,
  TEMINAT_VERME_TALEBI = 32,
  SATISA_ISTIRAK_TALEBI = 30,
  ITIRAZ_INCELEME_TALEBI = 23,
}

export enum DavaTalepler {
  BELGE_YUKLEME_TALEBI = 3,
  DOSYA_ACMA_TALEBI = 16,
  TEMINAT_IADE_TALEBI = 33,
  TEMINAT_VERME_TALEBI = 32,
  SATISA_ISTIRAK_TALEBI = 30,
  KARAR_DUZELTMEYE_GITME_TALEBI = 27,
  TEMYIZE_GITMEME_TALEBI = 26,
  DAVA_HITAM_TALEBI = 28,
  DAVA_EMSAL_TALEBI = 15,
}

export enum TalepTipi {
  AVANS_TALEBI = 1, // userd
  DOSYA_DUSURME_TALEBI = 2, // userd
  BELGE_YUKLEME_TALEBI = 3, // userd
  DOSYA_IADE_TALEBI = 4, // userd
  MASRAF_KAPAMA_TALEBI = 5, // userd
  PARA_YATTI_TALEBI = 6, // userd
  TMD_DURUMUNDAN_CIKARMA_TALEBI = 8, // userd
  MASRAF_GERI_ALMA_TALEBI = 9, // userd
  DAVA_VEKALET_UCRETI_ONAYI_TALEBI = 10, // userd
  ALEYHE_ODEME_TALEBI = 11, // userd
  DOSYA_ATAMA_TALEBI = 12, // userd
  MUKERRER_TAKIP_BASLATMA_ICIN_TAKIP_IPTAL_TALEBI = 13, // userd
  VEKIL_TALIMAT_TALEBI = 14, // userd
  DAVA_EMSAL_TALEBI = 15, // userd
  DOSYA_ACMA_TALEBI = 16, // userd
  BORC_DUSUM_TALEBI = 17, // userd
  BELGE_CEKME_TALEBI = 19, // userd
  INDIRIM_TALEBI = 24, // userd
  YENI_KULLANICI_EKLEME_TALEBI = 29, // userd
  MUTALAA_TALEBI = 18, // userd
  ITIRAZ_INCELEME_TALEBI = 23, // userd
  FINANS_UCRET_ONAY_TALEBI = 25, // userd
  DAVA_HITAM_TALEBI = 28, // userd
  TUTAR_DUZELTME_TALEBI = 22, // userd
  TEMYIZE_GITMEME_TALEBI = 26, // userd
  KARAR_DUZELTMEYE_GITME_TALEBI = 27, // userd
  TAHSILAT_GIRIS_TALEBI = 20, // userd
  TAHSILAT_IPTAL_TALEBI = 21, // userd
  SATISA_ISTIRAK_TALEBI = 30, // userd
  ALACAK_IADE_TALEBI = 31, // userd
  TEMINAT_VERME_TALEBI = 32, // userd
  TEMINAT_IADE_TALEBI = 33, // userd
  SISTEM_PARAMETRE_TALEP = 34, // userd
  FAIZ_INDIRIM_TALEP = 35, // userd
  KTVU_FERAGAT_TALEP = 36, // userd
  DAVA_MVU_ODEME_TALEP = 37, // userd
  BANKA_BORC_DUSUM_TALEP = 39,
  AVANS_IADE_TALEP = 40,
  KONFIGURASYON_PARAMETRELERI_TALEP = 41,
  FATURA_ISLEM_TALEP = 38 // userd
}

export enum BildirimDurumu {
  ISLEM_BASLADI = 1,
  GONDERILECEK = 2,
  GONDERILDI = 3,
  GONDERILMEYECEK = 4,
  CEVAP_DOSYASI_ISLENDI = 5,
  DOSYA_BULUNAMADI = 6,
  KAYITLAR_HAZIRLANDI = 7
}

export enum MalTipi {
  //Şirket bazında farklılaştığı için özellikle dropdownlistler'de kullanılması hataya sebep olur
  ARAC = 31,
  BANKA_HESAP = 11,
  GAYRI_MENKUL = 34,
  GEMI = 32,
  HISSE_SENEDI = 20,
  MAAS = 12,
  TICARI_ISLETME = 21,
  UCUNCU_SAHIS = 10,
  ESYA = 30,
  TARIM_URUNLERI = 36,
  HAYVAN = 35,
  UCAK = 33,
  DIGER = 99,
  PAMUK = 100,
  TUTUN = 101,
  PLASTIK = 102,
  TAKSI_PLAKASI = 103,
  MINIBUS_HATTI = 104,
  MARKA_DEGERİ = 105
}

export enum Oncelik {
  DUSUK = 1,
  ORTA = 2,
  YUKSEK = 3
}

export enum TaksitlendirmeTipi {
  KAMPANYA = 1,
  OZEL_SULH = 2,
  RESMI_SULH = 3,
  RESMI_TAAHHUT = 4
}

export enum HarcKesilmeDurumu {
  KESILMEYECEK = 1,
  KESILECEK = 2,
  KESILDI = 3,
}

export enum FarkYansitilacakTaksit {
  SON_TAKSIDE_YANSIT = 1,
  YENI_TAKSIDE_YANSIT = 2
}

export enum BorcKalemIcra {
  FATURALI_ANA_TUTAR = 1,
  FATURALI_GECIKME = 2,
  FATURASIZ_GECIKME = 3,
  TAKSITLENDIRME_BEDELI = 4,
  KIDEM_TAZMINATI_FATURALI = 16,
  KIDEM_TAZMINATI_FATURASIZ = 17,
  IHBAR_TAZMINATI_FATURALI = 18,
  IHBAR_TAZMINATI_FATURASIZ = 19,
  MADDI_TAZMINAT = 20,
  MANEVI_TAZMINAT = 21,
  ISCI_ALACAGI_FATURALI = 22,
  ISCI_ALACAGI_FATURASIZ = 23,
  FAZLA_MESAI_ALACAGI_FATURALI = 24,
  FAZLA_MESAI_ALACAGI_FATURASIZ = 25,
  HASAR_BEDELI_FATURALI = 26,
  HASAR_BEDELI_FATURASIZ = 27,
  KIRA_ALACAGI_FATURALI = 48,
  YARGILAMA_GIDERI = 30,
  DAVA_VEKALET_UCRETI = 28,
  FATURALI_GECIKME_KDV = 63,
  CARI_HESAP = 64,
  KAMBIYO_ALACAGI = 65,
  TAZMINAT = 66,
  KOMISYON = 67,
  GECIS_UCRETI = 75,
  CEZA_TUTARI = 76,
  MADDI_TAZMINAT_FATURALI = 73,
  KAMPANYA_CIHAZ_BEDELI_FATURASIZ = 49,
  DAMGA_VERGISI = 68,
  ANA_TUTAR = 79,
  DAVA_FAIZI = 91,
  DAVA_MASRAFI = 92
}

export enum BorcKalemDava {
  ICRA_INKAR_TAZMINATI_DAVA = 9,
  DIGER_DAVA = 14,
  KIDEM_TAZMINATI_FATURALI_DAVA = 36,
  KIDEM_TAZMINATI_FATURASIZ_DAVA = 37,
  IHBAR_TAZMINATI_FATURALI_DAVA = 38,
  IHBAR_TAZMINATI_FATURASIZ_DAVA = 39,
  MADDI_TAZMINAT_DAVA = 40,
  MANEVI_TAZMINAT_DAVA = 41,
  ISCI_ALACAGI_FATURALI_DAVA = 42,
  ISCI_ALACAGI_FATURASIZ_DAVA = 43,
  FAZLA_MESAI_ALACAGI_FATURALI_DAVA = 44,
  FAZLA_MESAI_ALACAGI_FATURASIZ_DAVA = 45,
  HASAR_BEDELI_FATURALI_DAVA = 46,
  HASAR_BEDELI_FATURASIZ_DAVA = 47,
  ALACAK_FATURALI = 60,
  ALACAK_FATURASIZ = 61,
  ASIL_ALACAK_FATURALI = 31,
  DAVA_KARARI_FAIZ_FARKI = 58,
  YARGILAMA_GIDERI_DAVA = 59,
  MADDI_TAZMINAT_FATURALI_DAVA = 74,
  ANA_TUTAR_DAVA = 80,
  ICRA_MASRAFI_OLASI = 90,
  ICRA_TAHSIL_HARCI_OLASI = 89,
}

export enum BorcKalemIcraDava {
  FATURALI_ANA_TUTAR = 1,
  FATURALI_GECIKME = 2,
  FATURASIZ_GECIKME = 3,
  TAKSITLENDIRME_BEDELI = 4,
  KIDEM_TAZMINATI_FATURALI = 16,
  KIDEM_TAZMINATI_FATURASIZ = 17,
  IHBAR_TAZMINATI_FATURALI = 18,
  IHBAR_TAZMINATI_FATURASIZ = 19,
  MADDI_TAZMINAT = 20,
  MANEVI_TAZMINAT = 21,
  ISCI_ALACAGI_FATURALI = 22,
  ISCI_ALACAGI_FATURASIZ = 23,
  FAZLA_MESAI_ALACAGI_FATURALI = 24,
  FAZLA_MESAI_ALACAGI_FATURASIZ = 25,
  HASAR_BEDELI_FATURALI = 26,
  HASAR_BEDELI_FATURASIZ = 27,
  KIRA_ALACAGI_FATURALI = 48,
  YARGILAMA_GIDERI = 30,
  DAVA_VEKALET_UCRETI = 28,
  FATURALI_GECIKME_KDV = 63,
  CARI_HESAP = 64,
  KAMBIYO_ALACAGI = 65,
  TAZMINAT = 66,
  KOMISYON = 67,
  GECIS_UCRETI = 75,
  CEZA_TUTARI = 76,
  MADDI_TAZMINAT_FATURALI = 73,
  KAMPANYA_CIHAZ_BEDELI_FATURASIZ = 49,
  DAMGA_VERGISI = 68,
  ANA_TUTAR = 79,
  DAVA_FAIZI = 91,
  DAVA_MASRAFI = 92,
  ICRA_INKAR_TAZMINATI_DAVA = 9,
  DIGER_DAVA = 14,
  KIDEM_TAZMINATI_FATURALI_DAVA = 36,
  KIDEM_TAZMINATI_FATURASIZ_DAVA = 37,
  IHBAR_TAZMINATI_FATURALI_DAVA = 38,
  IHBAR_TAZMINATI_FATURASIZ_DAVA = 39,
  MADDI_TAZMINAT_DAVA = 40,
  MANEVI_TAZMINAT_DAVA = 41,
  ISCI_ALACAGI_FATURALI_DAVA = 42,
  ISCI_ALACAGI_FATURASIZ_DAVA = 43,
  FAZLA_MESAI_ALACAGI_FATURALI_DAVA = 44,
  FAZLA_MESAI_ALACAGI_FATURASIZ_DAVA = 45,
  HASAR_BEDELI_FATURALI_DAVA = 46,
  HASAR_BEDELI_FATURASIZ_DAVA = 47,
  ALACAK_FATURALI = 60,
  ALACAK_FATURASIZ = 61,
  ASIL_ALACAK_FATURALI = 31,
  DAVA_KARARI_FAIZ_FARKI = 58,
  YARGILAMA_GIDERI_DAVA = 59,
  MADDI_TAZMINAT_FATURALI_DAVA = 74,
  ANA_TUTAR_DAVA = 80,
  ICRA_MASRAFI_OLASI = 90,
  ICRA_TAHSIL_HARCI_OLASI = 89,
}

export enum BorcKalem {
  FATURALI_ANA_TUTAR = 1,
  FATURALI_GECIKME = 2,
  FATURASIZ_GECIKME = 3,
  TAKSITLENDIRME_BEDELI = 4,
  ICRA_VEKALET_UCRETI = 5,
  DAVA_VEKALET_UCRETI_DAVA = 6,
  ICRA_INKAR_TAZMINATI_DAVA = 9,
  DIGER_DAVA = 14,
  KIDEM_TAZMINATI_FATURALI = 16,
  KIDEM_TAZMINATI_FATURASIZ = 17,
  IHBAR_TAZMINATI_FATURALI = 18,
  IHBAR_TAZMINATI_FATURASIZ = 19,
  MADDI_TAZMINAT = 20,
  MANEVI_TAZMINAT = 21,
  ISCI_ALACAGI_FATURALI = 22,
  ISCI_ALACAGI_FATURASIZ = 23,
  FAZLA_MESAI_ALACAGI_FATURALI = 24,
  FAZLA_MESAI_ALACAGI_FATURASIZ = 25,
  HASAR_BEDELI_FATURALI = 26,
  HASAR_BEDELI_FATURASIZ = 27,
  KIDEM_TAZMINATI_FATURALI_DAVA = 36,
  KIDEM_TAZMINATI_FATURASIZ_DAVA = 37,
  IHBAR_TAZMINATI_FATURALI_DAVA = 38,
  IHBAR_TAZMINATI_FATURASIZ_DAVA = 39,
  MADDI_TAZMINAT_DAVA = 40,
  MANEVI_TAZMINAT_DAVA = 41,
  ISCI_ALACAGI_FATURALI_DAVA = 42,
  ISCI_ALACAGI_FATURASIZ_DAVA = 43,
  FAZLA_MESAI_ALACAGI_FATURALI_DAVA = 44,
  FAZLA_MESAI_ALACAGI_FATURASIZ_DAVA = 45,
  HASAR_BEDELI_FATURALI_DAVA = 46,
  HASAR_BEDELI_FATURASIZ_DAVA = 47,
  KIRA_ALACAGI_FATURALI = 48,
  YARGILAMA_GIDERI = 30,
  DAVA_VEKALET_UCRETI_ICRA = 28,
  ALEYHE_TAKIBE_ESAS_ALACAK_DAVA = 50,
  ALEYHE_VEKALET_UCRETI_DAVA = 51,
  ALEYHE_MASRAF_DAVA = 52,
  ALEYHE_TAHSIL_HARCI_DAVA = 53,
  ALEYHE_ESAS_ALACAK = 54,
  ALEYHE_VEKALET_UCRETI = 55,
  ALEYHE_MASRAF = 56,
  ALEYHE_TAHSIL_HARCI = 57,
  ALACAK_FATURALI = 60,
  ALACAK_FATURASIZ = 61,
  ASIL_ALACAK_FATURALI = 31,
  FATURALI_GECIKME_KDV = 63,
  ALEYHE_YARGILAMA_GIDERI_DAVA = 62,
  DAVA_KARARI_FAIZ_FARKI = 58,
  YARGILAMA_GIDERI_DAVA = 59,
  KLASOR_GECIKME_BEDELI = 70,
  ALEYHE_KLASOR_TUTARI = 71,
  ALEYHE_KLASOR_GECIKME_BEDELI = 72,
  CARI_HESAP = 64,
  KLASOR_TUTARI = 69,
  KAMPANYA_CIHAZ_BEDELI_FATURASIZ = 49,
  KAMBIYO_ALACAGI = 65,
  TAZMINAT = 66,
  KOMISYON = 67,
  GECIS_UCRETI = 75,
  CEZA_TUTARI = 76,
  MADDI_TAZMINAT_FATURALI = 73,
  MADDI_TAZMINAT_FATURALI_DAVA = 74,
  DAMGA_VERGISI = 68,
  ALEYHE_ARABULUCU_UCRETI_DAVA = 93,
  ALEYHE_FAIZ = 77,
  ALEYHE_FAIZ_DAVA = 78,
  CEK_TUTARI = 8100,
  DIGER_GAYRI_NAKDI_RISK = 8200,
  BONO_KOMISYONU = 1200,
  CEK_TAZMINATI = 1300,
  KGF_MASRAF = 9300,
  ANA_TUTAR_ICRA = 79,
  ANA_TUTAR_DAVA = 80,
  ALEYHE_ANA_TUTAR_ICRA = 81,
  ALEYHE_ANA_TUTAR_DAVA = 82,
  ALEYHE_ICRA_VEKALET_UCRETI_OLASI = 83,
  ALEYHE_ICRA_MASRAF_OLASI = 84,
  ALEYHE_ICRA_TAHSIL_HARCI_OLASI = 85,
  ALEYHE_DAVA_FAIZI = 86,
  ALEYHE_DAVA_MASRAF_ICRA = 87,
  ALEYHE_DAVA_VEKALET_UCRETI_ICRA = 88,
  ICRA_MASRAFI_OLASI = 90,
  ICRA_TAHSIL_HARCI_OLASI = 89,
  DAVA_FAIZI = 91,
  DAVA_MASRAFI = 92,
  ANA_PARA_TUTARI = 1000,
  KUR_FARKI = 1100,
  KUR_FARKI_BSMV = 1110,
  KUR_FARKI_KKDF = 1120,
  FAIZ_TAHAKKUK_TUTARI = 2000,
  EKSTRELESMIS_FAIZ_TUTARI = 2100,
  EKSTRELESMIS_VERGI_TUTARI = 2200,
  AKDI_FAIZ_TUTARI = 2300,
  AKDI_FAIZ_BSMV = 2310,
  AKDI_FAIZ_KKDF = 2320,
  TEMERRUT_TUTARI = 2400,
  TEMERRUT_BSMV = 2410,
  TEMERRUT_KKDF = 2420,
  KOMISYON_TUTARI = 2500,
  KOMISYON_TUTARI_BSMV = 2510,
  KOMISYON_TUTARI_KKDF = 2520,
  YASAL_TAKIP_ONCESI_MASRAF = 3000,
  YASAL_TAKIP_SONRASI_MASRAF = 3100,
  YASAL_TAKIP_SONRASI_MASRAF_BSMV = 3110,
  VEKALET_UCRETI = 4000,
  TAHSIL_HARCI = 5000,
  CEYP = 6000,
  YASAL_TAKIP_ONCESI_MASRAF_BSMV = 3010,
  IADE_TUTARI = 7000,
  ALEYHE_ARABULUCU_UZLASMA_TUTARI = 94,
  KGF_TANZIM_OZKAYNAK = 9101,
  KGF_TANZIM_HAZINE = 9102,
  KGF_FAIZ_OZKAYNAK = 2901,
  KGF_FAIZ_HAZINE = 2902
}

export enum MukerrerIcraSebebi {
  HATALI_BORCLU_BILGISI = 1,
  ITIRAZ_IPTALI_ZAMAN_ASIMI = 2,
  VEFAT_BILINMEDEN_BASLATILAN_ICRA_TAKIBI = 3,
  DOSYA_ICRADA_KAYBOLMUS = 4,
  SAHTE_KIMLIK = 5
}

export enum TakipTipi {
  ILAMSIZ_TAKIP = 1,
  REHNIN_PARAYA_CEVRILMESI_YOLUYLA = 2,
  KIRA_KIRA_FARKI = 3,
  ILAMLI_ALACAK = 4,
  ILAMLI_MENKUL_TAHLIYE = 5,
  COCUK_TESLIMI = 6,
  ILAMSIZ_TAHLIYE = 7,
  IPOTEGIN_PARAYA_CEVRILMESI_YOLUYLA = 8,
  IPOTEK_ODEME_EMRI = 9,
  KAMBIYO_SENETLERINE_OZGU_HACIZ_YOLUYLA_TAKIP = 10,
  IFLAS_YOLUYLA_ICRA_TAKIBI = 11
}

export enum IcomSeviye {
  TRACE = 1,
  DEBUG = 2,
  INFO = 3,
  WARN = 4,
  ERROR = 5,
  FATAL = 6,
  OFF = 7
}

export enum KdvOrani {
  KDV_0 = 1,
  KDV_1 = 2,
  KDV_8 = 3,
  KDV_18 = 4,
  KDV_10 = 5,
  KDV_20 = 6
}

export enum BorcAlacak {
  BORC = 1,
  ALACAK = 2
}

export enum BorcGrubu {
  TAKIBE_ESAS_ALACAK = 1,
  FAIZ = 2,
  MASRAF = 3,
  VEKALET_UCRETI = 4,
  TAHSIL_HARCI = 5,
  CEYP = 6,
  BSMV = 7,
  GAYRI_NAKDI_RISK = 8,
  KREDI_GARANTI_FONU = 9,
  ALEYHE_TAKIBE_ESAS_ALACAK = 11,
  ALEYHE_FAIZ = 12,
  BONO_KOMISYONU = 15,
  CEK_TAZMINATI = 16,
  DAVA_HARCLARI = 22,
  IADE_TUTARI = 31,
  DAMGA_VERGISI = 32,
  DAVA_DEGERI = 33,
  ALEYHE_DAVA_DEGERI = 34,
}

export enum BorcGrubuBorcGrubuIslem {
  TAKIBE_ESAS_ALACAK = 1,
  FAIZ = 2,
  MASRAF = 3,
}

export enum MasrafTipi {
  VERI_AKTARIM_ILK_ICRA_MASRAFI = 1,
  VERI_AKTARIM_DIGER_MASRAF = 2,
  BASVURU_HARCI = 10,
  VEKALET_HARCI = 11,
  HARICI_TAHSIL_HARCI_MASRAFI = 12,
  PESIN_HARC = 13,
  FERAGAT_HARCI = 15,
  ITIRAZ_PULU = 16,
  BARO_PULU_VEKALET_PULU = 17,
  DOSYA_UCRETI = 18,
  BEDELSIZ_ISLEM = 34
}

export enum MasrafPaylasimi {
  DOSYALAR_ARASINDA_PAYLASTIRILACAK = 0,
  HER_DOSYA_ICIN_AYRI_EKLENECEK = 1
}

export enum SozlesmeTipi {
  IDARI_TAKIP_SOZLESMESI = 69,
  SADECE_ICRA = 18,
  ICRA_VE_DAVA = 19,
  SADECE_DAVA = 20,
  KADROLU = 21,
  DEVIR_ONCESI = 55,
}

export enum EklenmeSebebi {
  TAKIP_BASLATMA = 1,
  ICRA_YENILEME = 2,
  MUKERRER_TAKIP_BASLATMA = 3,
  MANUEL_EKLEME = 4,
  HACIZ_PLANLAMA = 5,
  VEKIL_DEGISIKLIGI = 6,
  HACIZ_FEKKI = 7,
  HARICEN_YUKLEME = 8,
  GECMIS_YILA_AIT_MASRAFIN_SILINMESI = 10,
  HACIZ_SONUCU_GIRISI = 11,
  DAVA_ACMA = 12,
  UYAP = 13
}

export enum TakipSebebi {
  ABONELIK = 1,
  HASAR = 2,
  ULASTIRMA = 4,
  ALACAK = 5,
  HUKUK = 6,
  TUKETICI_SIKAYETI = 7,
  DIGER = 9
}

export enum HacizDurumu {
  PLANLANDI = 1,
  HACIZ_ERTELENDI = 2,
  HACZE_KABIL_MAL_BULUNAMADI = 3,
  ADRES_KAPALI = 4,
  MENKUL_HACZI_YAPILDI = 5,
  BORCLU_TASINMIS = 6,
  HACIZ_IPTAL_EDILDI = 7,
  TAAHHUT_ALINDI = 8,
  ICRA_KEFILI_ALINDI = 9
}

export enum IhtiyatiHacizDurumu {
  BASVURU_BEKLENIYOR = 1,
  BASVURU_YAPILMAYACAK = 2,
  IHTIYATI_HACIZDEN_VEZGECILDI = 3,
  IHTIYATI_HACIZ_KARARI_ALINDI = 4,
  IHTIYATI_HACIZ_KARARI_REDDEDILDI = 5,
  IHTIYATI_HACIZ_DUSTU = 6,
  BASVURU_YAPILDI_KARAR_BEKLENIYOR = 7
}

export enum IletisimTipi {
  CEP_TELEFONU = 1,
  EV_TELEFONU = 2,
  E_POSTA = 3,
  YURTDISI_TELEFON = 4,
  IS_YERI_TELEFON = 5,
  KEP = 6,
  DIGER = 99
}

export enum IletisimKaynagi {
  VERI_AKTARIMI = 0,
  MUSTERI_SISTEMI = 1,
  ARASTIRMA = 2,
  BEYAN = 3,
  TELEFON_ARAMA_CLIP = 4,
  CAGRI_MERKEZI_CLIP = 5,
  DIS_TESPIT = 6,
  DIGER = 7,
  CAGRI_MERKEZI_CLIP_MUSTERI_BEYANI = 8
}

export enum IletisimGecerligi {
  CEVAP_VERMIYOR = 1,
  BASKA_BIRINE_AIT = 2,
  GECERSIZ = 3,
  GECERLI = 4,
  BELIRSIZ = 5
}

export enum Bolum {
  YASAL_TAKIP = 1,
  DAVA_TAKIP = 2,
}

export enum PrimeEsasTutar {
  ITC_TUTARI = 1,
  TAHSILAT_TUTARI = 2
}

export enum TebligKisiTipi {
  KENDISI = 1,
  ESI = 2,
  OGLU = 3,
  KIZI = 4,
  KARDESI = 5,
  KOMSUSU = 6,
  CALISANI = 7,
  MUHTAR = 8,
  ANNESI = 9,
  BABASI = 10,
  BUYUKELCILIK = 11,
  TEBLIG35EGORE = 12,
  DIGER = 14,
  TEBLIG21EGORE = 15,
  TEBLIG36GORE = 16
}

export enum TebligDurumu {
  TEBLIGAT_YAPILMAMIS = 1,
  CEVAP_BEKLENIYOR = 2,
  BILA_TEBLIG = 3,
  TEBLIG_EDILDI = 4
}

export enum BilaTebligSebebi {
  TASINMIS = 1,
  ADRES_YETERSIZ = 2,
  ADRES_YANLIS = 3,
  TANINMIYOR = 4,
  OLMUS = 5,
  YURTDISINDA = 6,
  CEZAEVINDE = 7,
  ASKERDE = 8
}

export enum MesajDurum {
  OKUNDU = 1,
  OKUNMADI = 2,
  SILINDI = 3,
  CEVAPLANDI = 4,
  TALEP_ACIK = 5,
  TALEP_KAPALI = 6
}

export enum MesajTipi {
  MAIL = 1,
  DUYURU = 2,
  TALEP = 3
}

export enum MesajTalepTipi {
  ISTEK = 1,
  ONERI = 2,
  SIKAYET = 3
}

export enum FaturaTipiFaturaDosyasi {
  TAHSILAT_FATURASI = 6,
  TAHSILAT_IPTAL_FATURASI = 7,
  AVANS_FAIZ_FATURASI = 8
}

export enum FaturaOnayDurumu {
  ONAY_BEKLIYOR = 1,
  ONAYLANDI = 2
}

export enum BaglantiTipi {
  SMS = 1,
  EPOSTA = 2,
  Webservis = 3,
  FTP = 4,
  HTTP = 5
}

export enum TahsilatKanali {
  EMANET = 1,
  BAYI = 2,
  GISE = 3,
  TMH = 4,
  WSC = 5,
  ICRA_MUDURLUGU = 6,
  VEKIL = 7,
  BANKA = 8,
  NAKIT = 51,
  KREDI_KARTI_POS = 30,
  VPOS = 54,
  KGF_GIRISI = 1000,
  HGS = 55,
  OGS = 56,
  KREDI_KARTI_GISE = 53
}

export enum IlkIcraDokumleri {
  TAKIP_TALEBI = 1,
  ICRA_TENSIP_ZABTI = 2,
  ODEME_ICRA_TAHLIYE_EMRI = 3,
  TEBLIG_ZARFI = 4,
  SERH_150_C_MUZEKKERESI = 5,
  SERH_150_C_TALEBI = 6,
  YAKALAMA_TALEBI = 7,
  IGB_LISTESI = 8,
  DELIL_FOTO_LISTESI = 9
}

export enum IlkIcraListeleri {
  ORTAK_AVUKAT_MASRAF_LISTESI = 1,
  ACILAN_TAKIPLERE_AIT_MASRAF_LISTESI = 2,
  ACILAN_TAKIPLERE_AIT_HARC_LISTESI = 3,
  POSTA_GONDERI_UCRET_LISTESI = 4,
  PTT_TEBLIGAT_TEVDII_LISTESI = 5
}

export enum DokumGrubu {
  TAKIP_TALEBI = 1,
  TEBLIG_TALEBI = 2,
  ADRES_ARASTIRMA_TALEBI = 3,
  MAL_VARLIGI_ARASTIRMA_VE_HACIZ_TALEBI = 4,
  HACIZ_TALEBI = 5,
  ARAC_MUHAFAZASI_TALEBI = 6,
  KIYMET_TAKDIRI_TALEBI = 7,
  SATIS_TALEBI = 8,
  HACIZ_FEKKI_TALEBI = 9,
  DIGER_TALEP = 10,
  ODEME_ICRA_TAHLIYE_EMRI = 11,
  DAVET_KAGIDI = 12,
  MAKBUZ = 13,
  TEBLIG_ZARFI = 14,
  ILAN = 15,
  DIGER_DOKUM = 16,
  ADRES_ARASTIRMA_MUZEKKERESI = 17,
  HACIZ_MUZEKKERESI = 18,
  ARAC_MUHAFAZASI_MUZEKKERESI = 19,
  SATIS_MUZEKKERESI = 20,
  HACZIN_FEKKI_MUZEKKERESI = 21,
  DIGER_MUZEKKERE = 22,
  TALIMAT_DOKUM = 23,
  ICRA_DAVASI_DOKUMLERI = 24,
  TEHRI_ICRA_DOKUM = 25,
  MEKTUPLAR = 26,
  DIGER_DAVA_DOKUMLERI = 27,
  TEMINAT_TALEP_DOKUMLERI = 37,
  TEMINAT_TALEP_DOKUMLERI_DAVA = 38
}

export enum HaftaninGunu {
  PAZARTESI = 1,
  SALI = 2,
  CARSAMBA = 3,
  PERSEMBE = 4,
  CUMA = 5,
  CUMARTESI = 6,
  PAZAR = 7
}

export enum PersonelOrijin {
  TEB = 1,
  FORTIS = 2,
  STAJYER = 3,
  OUTSOURCE = 4
}

export enum PersonelFesihTuru {
  IAF = 1,
  ISTIFA = 2,
  EMEKLILIK = 3
}

export enum PersonelFesihKonusu {
  PERFORMANS = 1,
  DIKOM = 2,
  ON_BES_YIL = 3,
  IS_DEGISIKLIGI = 4,
  EMEKLILIK = 5
}

export enum OnayDurumu {
  ONAY_SURECI_BASLADI = 10,
  ONAY_SURECI_DEVAM_EDIYOR = 11,
  ONAY_SURECI_TAMAMLANDI_ONAY = 12,
  ONAY_SURECI_TAMAMLANDI_RED = 13,
  BELGE_INCELEME_BEKLENIYOR = 101,
  BELGE_INCELENIYOR = 102,
  BELGE_INCELEME_CEVAP_GUVENLI = 103,
  BELGE_INCELEME_CEVAP_GUVENLI_DEGIL = 104
}

export enum ReddiyatOnayDurumu {
  ONAY_BEKLIYOR = 1,
  ASKIYA_ALINDI = 2,
  ONAY_SURECI_BASLADI = 10,
  ONAY_SURECI_DEVAM_EDIYOR = 11,
  ONAY_SURECI_TAMAMLANDI_ONAY = 12,
  ONAY_SURECI_TAMAMLANDI_RED = 13,
  BELGE_INCELEME_BEKLENIYOR = 101,
  BELGE_INCELENIYOR = 102,
  BELGE_INCELEME_CEVAP_GUVENLI = 103,
  BELGE_INCELEME_CEVAP_GUVENLI_DEGIL = 104
}

export enum OnaySurecTipi {
  MASRAF_KAPAMA_TALEBI = 1,
  AVANS_TALEBI = 2,
  SERBEST_MESLEK_MAKBUZU = 3,
  BANKA_BORC_DUSUM_TALEBI = 4
}

export enum BankBorcDusumOnaySurecTipi {
  BANKA_BORC_DUSUM_TALEBI_AKTIFTEN_SILME = 5,
  BANKA_BORC_DUSUM_TALEBI_FAIZ_FERAGAT = 6
}

export enum OnaySurecIslemKodu {
  ONAY_SURECI_BASLATMA = 1230,
  ONAY_SURECI_ONAY = 1231,
  ONAY_SURECI_RED = 1232,
  ONAY_SURECI_TAMAMLANDI = 1233
}

export enum OnaySurecOnayDurumu {
  ONAY_SURECI_BASLADI = 10,
  ONAY_SURECI_DEVAM_EDIYOR = 11,
  ONAY_SURECI_TAMAMLANDI_ONAY = 12,
  ONAY_SURECI_TAMAMLANDI_RED = 13
}

export enum TeminatTipi {
  NAKIT = 1, MEKTUP = 2, IPOTEK = 3, KAMBIYO = 4, REHIN = 5, ALINAN_MEKTUP = 6
}

export enum AlinanTeminatTipi {
  IPOTEK = 3, KAMBIYO = 4, REHIN = 5
}

export enum TeminatYonu {
  LEHE = 1, ALEYHE = 2, KURUM_TEMINATI = 3, KARSI_TARAF_TEMINATI = 4
}

export enum RehinTipi {
  ARAC = 1,
  EMTIA = 2,
  TASINIR = 3
}

export enum BordroDurum {
  FINANSA_ILETILMEYI_BEKLIYOR = 1,
  ON_KAYIT_FINANSA_ILETILDI = 2,
  ON_KAYIT_KESINLESTI = 3,
  IPTAL_EDILDI = 4,
  EKSIK_HATALI_BELGE = 5,
  FH_SMM_YE_DAHIL_OLMAYI_BEKLIYOR = 6,
  FH_SMM_YE_DAHIL_EDILDI = 7,
  FH_ODENMEZ = 8,
  SMM_UST_VEKIL_ONAYI_BEKLIYOR = 9,
  SMM_HUKUK_ONAYI_BEKLIYOR = 10,
  SMM_HUKUK_ONAY_SURECINDE = 11,
  SMM_TEBIS_E_ILETILMEYI_BEKLIYOR = 12,
  SMM_TEBIS_E_ILETILDI = 13,
  SMM_REDDEDILDI = 14,
  BELGE_EKLENMESI_BEKLENIYOR = 16
}

export enum SmmDurum {
  SMM_YE_DAHIL_OLMAYI_BEKLIYOR = 6,
  SMM_YE_DAHIL_EDILDI = 7,
  ODENMEZ = 8,
  TAHSILAT_ONAY_SURECINDE = 15,
}

export enum FinansalHareketDurum {
  TEBIS_E_ILETILMEYI_BEKLIYOR = 1,
  HUKUK_ONAYI_BEKLIYOR = 2,
  TEBIS_E_ILETILDI = 3,
  TEBIS_TE_SONUCLANDI = 4,
  TEBIS_TE_IPTAL_EDILDI = 5,
  GONDERILMEYECEK = 6
}

export enum AdresTipiEnums {
  YURT_ICI_IKAMETGAH_ADRESI = 1,
  YURT_ICI_ISYERI_ADRESI = 2,
  DEPO_ADRESI = 3,
  ASKERLIK_ADRESI = 4,
  YURT_DISI_IKAMETGAH_ADRESI = 5,
  YURT_DISI_ISYERI_ADRESI = 6,
  CEZAEVI_ADRESI = 7,
  SIRKET_MERKEZI = 8,
  AVUKATLIK_ADRESI = 9,
  CEZA_INFAZ_KURUMU_ADRESI = 10,
  ELEKTRONIK_TEBLIGAT_ADRESI = 11,
  ESKI_ELEKTRONIK_TEBLIGAT_ADRESI = 12,
  ESKI_MERNIS_ADRESI = 13,
  MERNIS_ADRESI = 14,
  MERSIS_ADRESI = 15
}

export enum OdemeTipi {
  PESIN = 0,
  KK = 1,
  MAHSUBEN = 2,
  AVANS_DAGITIM = 3,
  MAAS_HACZI = 4,
  TASINIR_SATISI_3_KISI = 5,
  TASINIR_SATISI_ALACAGA_MAHSUBEN = 6,
  TASINMAZ_SATISI_3_KISI = 7,
  TASINMAZ_SATISI_ALACAGA_MAHSUBEN = 8,
  TAKASTAN_CEK = 9,
  SIGORTA = 10,
  KGF = 11,
  KISIYE_TEMLIK_3_KISI = 12,
  ODEME_TIPI_89_1 = 13,
  KISIYE_TEMLIK_3_KISI_BIREYSEL = 14,
}

export enum IlamKaynagi {
  MAHKEME_KARARI = 1,
  ILAM_NITELIGINDE_BELGE = 2
}

export enum TahsilatIslemTurleri {
  TAHSILAT = 111,
  TAHSILAT_IPTAL = 311
}

export enum BorcDusumIslemTurleri {
  BORC_DUSUM = 114,
  BORC_DUSUM_IPTAL_BILDIRIM = 314
}

export enum SupheliAlacakIslemTurleri {
  HUKUK_DOSYA_OLUSTUR = 100,
  HUKUK_DOSYA_OLUSTUR_IPTAL = 300,
  ICRA_ACMA = 210,
  ICRA_ACILIS_IPTAL = 410,
  TERKIN = 120,
  TERKIN_IPTAL = 320,
  CEZA_TAHAKKUK = 1158,
  CEZA_TAHAKKUK_IPTAL = 1658
}

export enum TeminatSebebi {
  IHTIYATI_HACIZ = 1,
  SIRA_CETVELI = 2,
  TASARRUFUN_IPTALI = 3,
  TEHIRI_ICRA = 4,
  KIYMETLI_EVRAK_IPTALI = 5,
  IHTIYATI_TEDBIR = 6,
  MEHIL_VESIKASI = 7
}

export enum VerilenTeminatTipi {
  NAKIT = 1, MEKTUP = 2
}
export enum BagliDosya {
  ALT_DOSYA= 9, ILGILI = 8
}
export enum BagliDosyaKlasorDavaBaglamaNedeni {
 ALT_DOSYA= 9, DAVBIR=1,DAVAYR=2, ILGILI = 8
}
export enum ItirazSebebi {
  FATURA_ITIRAZI = 1,
  FRAUD_ITIRAZI = 2
}

export enum ItirazSekli {
  YAZILI = 1,
  SOZLU = 2,
}

export enum KimlikDogrulamaDurumu {
  DOGRULAMA_BEKLIYOR = 0,
  DOGRULAMA_BASARILI = 1,
  DOGRULAMA_BASARISIZ = 2,
  BILGILERI_EKSIK_DOGRULAMA_YAPILMAYACAK = 3,
  BILGILERI_GUNCELLENDI_DOGRULAMA_BEKLIYOR = 4,
  DOGRULANMAYACAK = 5
}

export enum GercekTuzelTipi {
  GERCEK = 1,
  TUZEL = 2
}

export enum TahsilatGirisTalepTipi {
  ICRA_DAIRESI = 1,
  ICRA_DAIRESI_GEC_TESPIT = 2,
  BILGI_EKSIKLIGI = 3,
  VEKIL_KAYNAKLI = 4,
  DIGER = 5
}

export enum AdresKaynagiTipi {
  VERI_AKTARIMI = 1,
  MUZEKKERE = 2,
  MUSTERI_SISTEMI_TESIS_ADRESI = 3,
  MUSTERI_SISTEMI_TEBLIGAT_ADRESI = 4,
  CANLI_ABONELIK_SORGULAMA = 5,
  DIGER = 6,
  ARASTIRMA = 7,
  BEYAN = 8,
  ABONELIK_SOZLESMESI = 9,
  MAHKEME_ILAMI = 10,
  MUSTERI_IRTIBAT_ADRESI = 11,
  MERNIS = 12,
  UYAP = 13,
  EGM_KGM = 14
}

export enum KimlikVerilisNedeni {
  DOGUMDAN = 1,
  KAYIPTAN = 2,
  YENILEME = 3,
  EVLILIK = 4,
  BOSANMA = 5
}

export enum KimlikTipi {
  NUFUS_CUZDANI = 1,
  EHLIYET = 2,
  PASAPORT = 3,
  KURUM_KIMLIGI = 4,
  EVLENME_CUZDANI = 5,
  TSKKK = 6,
  TCAB = 7,
  KKTCKK = 9,
  TCYKB = 10,
  TCMK = 11,
  TBMMMK = 12,
  UMB = 13,
  NATOEB = 14,
  SEYBEL = 15,
  HUDGB = 16,
  GKOPL = 17,
  YMKK = 18,
  IKIB = 19,
  CALIZB = 20,
  VSKKB = 21,
  YBNC = 22,
  YTCEP = 25,
  ETLP = 26,
  ETYP = 27,
  ETGP = 28,
  ETKP = 29,
  TCGCPS = 30,
  HSMKK = 31,
  TCGKK = 32,
  YABPAS = 34,
  TCCPKK = 35,
  NOTKK = 37,
  GEACU = 38,
  GEKOKK = 39,
  KIBRIS_KIMLIK_BELGESI = 372,
  IKAMET_TESKERESI = 373,
  TCKK = 374
}

export enum OgrenimDurumu {
  OKURYAZAR_VE_ALTI = 0,
  ILK_OGRETIM = 1,
  ORTA_OGRETIM = 2,
  LISE = 3,
  YUKSEK_OGRENIM = 4,
  YUKSEK_LISANS = 5,
  DOKTORA = 6,
  OKUR_YAZAR_DEGIL = 7,
  YUKSEK_OKUL = 8
}

export enum DosyadanDusmeyeKalanGunSayisi {
  _7 = 7,
  _14 = 14,
  _30 = 30,
  _60 = 60,
  _90 = 90
}

export enum GayrimenkulTipi {
  BINA = 10,
  BAGIMSIZ_KONUT = 11,
  BAGIMSIZ_ISYERI = 12,
  ARSA = 20,
  ARAZI = 20,
  DIGER = 99,
  APARTMAN = 100,
  ATOLYE = 101,
  DEPO = 102,
  BAHCE = 103,
  CIFTLIK = 104,
  ISYERI = 105,
  IMALATHANE = 106,
  MESKEN = 107,
  FABRIKA = 108,
  DUKKAN = 109,
  DAIRE = 110,
  TARLA = 111,
  BAHCELI_EV = 112
}

export enum SGKMaasTespitDurumu {
  DOGRULAMA_BEKLIYOR = 0,
  TESPIT_EDILDI = 1,
  TESPIT_EDILMEDI = 2,
  BILGILERI_EKSIK_DOGRULAMA_YAPILMAYACAK = 3,
  BILGILERI_GUNCELLENDI_DOGRULAMA_BEKLIYOR = 4,
  DOGRULANMAYACAK = 5
}

export enum MusteriTipi {
  GERCEK_KISI_TICARI = 1,
  GERCEK_KISI = 2,
  TUZEL_KISI_TICARI = 3,
  TUZEL_KISI = 4
}

export enum MusteriIsKolu {
  DIGER = 0,
  OBM = 2,
  BIREYSEL = 4,
  TICARI = 5,
  KURUMSAL_K2 = 6,
  KOBI = 7,
  YILDIZ = 8,
  ISLETME = 9,
  KOBI_PLUS = 10,
  KURUMSAL_K1 = 11
}

export enum DegerlemeTipi {
  EKSPERTIZ = 1,
  KIYMET_TAKDIRI = 2,
  MUHAMMEN_BEDEL = 3
}

export enum TakyidatTipi {
  HACIZ = 1,
  IPOTEK = 2,
  REHIN = 3
}

export enum VuTarifeTipi {
  MAKTU = 4
}

export enum AdresTipi {
  YURT_ICI_IKAMETGAH_ADRESI = 1,
  YURT_ICI_ISYERI_ADRESI = 2,
  DEPO_ADRESI = 3,
  ASKERLIK_ADRESI = 4,
  YURT_DISI_IKAMETGAH_ADRESI = 5,
  YURT_DISI_ISYERI_ADRESI = 6,
  CEZAEVI_ADRESI = 7,
  SIRKET_MERKEZI = 8,
  AVUKATLIK_ADRESI = 9,
  CEZA_INFAZ_KURUMU_ADRESI = 10,
  ELEKTRONIK_TEBLIGAT_ADRESI = 11,
  ESKI_ELEKTRONIK_TEBLIGAT_ADRESI = 12,
  ESKI_MERNIS_ADRESI = 13,
  MERNIS_ADRESI = 14,
  MERSIS_ADRESI = 15
}

export enum ArabuluculukDurumu {
  ARABULUCUYA_GIDILMEDI = 1,
  ARABULUCUYA_GIDILDI = 2,
  ARABULUCUYA_GIDILDI_SONUCLANMASI_BEKLENIYOR = 3,
  ANLASMA = 7,
  GORUSME_SONUCUNDA_ANLASAMAMA = 8,
  GORUSME_YAPILMADAN_ANLASAMAMA = 9,
  ARABULUCULUGA_UYGUN_OLUNMAMASI = 10,
  KONUSUZ_KALMA_BASVURUCUNUN_VAZGECMESI = 11,
  YETKISIZLIK = 12,
  SEHVEN_KAYIT = 13,
  KISMI_ANLASMA = 14
}

export enum MGSBrans {
  MGS110 = 110,
  MGS115 = 115,
  MGS140 = 140,
  MGS150 = 150,
  MGS180 = 180,
  MGS185 = 185,
  MGS190 = 190,
  MGS191 = 191,
  MGS195 = 195,
  MGS196 = 196,
  MGS210 = 210,
  MGS211 = 211,
  MGS212 = 212,
  MGS213 = 213,
  MGS214 = 214,
  MGS220 = 220,
  MGS310 = 310,
  MGS311 = 311,
  MGS312 = 312,
  MGS313 = 313,
  MGS314 = 314,
  MGS410 = 410,
  MGS415 = 415,
  MGS418 = 418,
  MGS420 = 420,
  MGS421 = 421,
  MGS425 = 425,
  MGS431 = 431,
  MGS513 = 513,
  MGS514 = 514,
  MGS515 = 515,
  MGS517 = 517,
  MGS518 = 518,
  MGS519 = 519,
  MGS520 = 520,
  MGS525 = 515,
  MGS527 = 527,
  MGS529 = 529,
  MGS530 = 530,
  MGS551 = 551,
  MGS552 = 552,
  MGS553 = 553,
  MGS554 = 554,
  MGS556 = 556,
  MGS557 = 557,
  MGS558 = 558,
  MGS559 = 559,
  MGS560 = 560,
  MGS561 = 561,
  MGS562 = 562,
  MGS563 = 563,
  MGS564 = 564,
  MGS565 = 565,
  MGS567 = 567,
  MGS570 = 570,
  MGS580 = 580,
  MGS610 = 610,
  MGS611 = 611,
  MGS620 = 620,
  MGS621 = 621,
  MGS622 = 622,
  MGS623 = 623,
  MGS624 = 624,
  MGS801 = 801,
  MGS850 = 850,
  MGS860 = 860,
  MGS880 = 880,
  MGS999 = 999
}

export enum HazineBrans {
  HAZINE701 = 701,
  HAZINE702 = 702,
  HAZINE703 = 703,
  HAZINE704 = 704,
  HAZINE710 = 710,
  HAZINE712 = 712,
  HAZINE714 = 714,
  HAZINE715 = 715,
  HAZINE717 = 717,
  HAZINE718 = 718,
  HAZINE719 = 719,
  HAZINE720 = 720,
  HAZINE724 = 724,
  HAZINE725 = 725,
  HAZINE726 = 726,
  HAZINE727 = 727,
  HAZINE728 = 728,
  HAZINE729 = 729,
  HAZINE730 = 730,
  HAZINE731 = 731,
  HAZINE733 = 733,
  HAZINE734 = 734,
  HAZINE735 = 735,
  HAZINE736 = 736,
  HAZINE750 = 750,
  HAZINE757 = 757,
  HAZINE765 = 765,
  HAZINE766 = 766,
  HAZINE767 = 767,
  HAZINE768 = 768,
  HAZINE776 = 776,
  HAZINE777 = 777,
  HAZINE779 = 779,
  HAZINE780 = 780,
  HAZINE782 = 782,
  HAZINE785 = 785,
  HAZINE800 = 800,
  HAZINE801 = 801,
  HAZINE802 = 802
}

export enum KullanimTarzi {
  KTZ11 = 11,
  KTZ20 = 20,
  KTZ30 = 30,
  KTZ31 = 31,
  KTZ40 = 40,
  KTZ45 = 45,
  KTZ46 = 46,
  KTZ50 = 50,
  KTZ51 = 51,
  KTZ60 = 60,
  KTZ65 = 65,
  KTZ70 = 70,
  KTZ71 = 71,
  KTZ72 = 72,
  KTZ75 = 75,
  KTZ80 = 80,
  KTZ81 = 81,
  KTZ82 = 82,
  KTZ83 = 83,
  KTZ84 = 84,
  KTZ85 = 85,
  KTZ86 = 86,
  KTZ90 = 90,
  KTZ91 = 91,
  KTZ95 = 95,
  KTZ96 = 96,
  KTZ99 = 99
}

export enum SigortaTeminatTipi {
  MDDI = 1,
  MNV = 2,
  VFT = 3,
  MLLYT = 4,
  TDV = 5,
  DGKY = 6,
  HKKR = 7,
  KZKY = 8,
  DGR = 9
}

export enum RucuNedeni {
  KARSI_TARAF_KUSURLU = 1,
  URETICI_FIRMA_KUSURLU = 2,
  TETKIK = 3
}

export enum ParaBirimi {
  TL = 949,
  USD = 840,
  EURO = 978,
  AUD = 36,
  DKK = 214,
  MIST = 826,
  CHF = 756,
  SEK = 752,
  CAD = 124,
  KWD = 414,
  NOK = 578,
  SAR = 682,
  JPY = 392,
  BGN = 975,
  ROL = 946,
  RUR = 643,
  IRR = 364,
  CNY = 156,
  IDR = 586,
  QAR = 405,
  GR = 479
}

export enum CinsiyetTipi {
  ERKEK = 1,
  KADIN = 2
}

export enum DosyaYetkiTipi {
  TERKIN_DOSYALAR = 1,
  VEFATLI_DOSYALAR = 2,
  KILITLI_DOSYALAR = 3,
  ABONELIK_DOSYALARI = 4,
  DIGER_TAKIP_SEBEPLI_DOSYALAR = 5,
  ICRA_ACILMAMIS_DOSYALAR = 6,
  ICRA_ACILMIS_DOSYALAR = 7,
  TEHIRI_ICRA_OLAN_DOSYALAR = 8,
  TEHIRI_ICRA_OLMAYAN_DOSYALAR = 9,
  DAGITIM_TARIHI_GELMEYEN_DOSYALAR = 10,
  HUKUK_BAKIS_ACISI = 11,
  VEKIL_BAKIS_ACISI = 12,
  SORUMLULUGUNUZDA_OLMAYAN_DOSYALAR = 13,
  TALIMATLI_DOSYALAR = 14,
  BIRINCI_EL_DOSYALAR = 15,
  IKINCI_EL_DOSYALAR = 16,
  HUKUK_BAKIS_ACISI_VEKIL_DOSYA = 17,
  ITIRAZLI_DOSYALAR = 18,
  ALT_DOSYALAR = 19,
  FINANS_ONAYI_VERILMEMIS_DOSYALAR = 20,
  FINANS_ONAYI_VERILMIS_DOSYALAR = 21,
  KAPALI_DOSYALAR = 22
}

export enum SablonTipi {
  SMS_BILDIRIM = 1,
  EPOSTA_BILDIRIM = 2
}

export enum SmsGonderimTipi {
  TELEFON_NO = 1,
  TCKIMLIK_NO = 2
}

export enum KisiVarsayilanTumu {
  VARSAYILAN = 0,
  TUMU = 1
}

export enum BonoAsamasi {
  BILGILERI_EKSIK = 131,
  ASLININ_HAZIRLANMASI_BEKLENIYOR = 132,
  TAMAMLANDI = 133
}

export enum FaizTipi {
  REESKONT_ISKONTO = 1,
  ADI_KANUNI = 2,
  DIGER = 3,
  REESKONT_AVANS = 7,
  UFE = 9,
  TUFE = 10,
  EN_YUKSEK_MEVDUAT_FAIZI_TL = 11,
  EN_YUKSEK_MEVDUAT_FAIZI_USD = 12,
  EN_YUKSEK_MEVDUAT_FAIZI_EUR = 13,
  EN_YUKSEK_MEVDUAT_FAIZI_PRF = 14,
  EN_YUKSEK_MEVDUAT_FAIZI_DEM = 15,
  EN_YUKSEK_BANKA_MEVDUAT_FAIZI = 16,
  GECIKME_FAIZI = 17,
  YASAL_FAIZ = 18,
  GECIKME_ZAMMI_KDV_HARICEN = 20,
  FAIZ_YOK = 47,
  TT_GECIKME_FAIZ_ORANI_VERGI_DAHIL = 99,
  AVEA_YASAL_FAIZ_PROFİL_1 = 100,
  SABIT_FAIZ_ORANI = 2000
}

export enum AskiyaAlmaSebebi {
  SAHTE_KIMLIK = 1,
  HATALI_TAHAKKUK = 2
}

export enum UrunAltTuru {
  KREDI_KARTI = 1,
  KMH = 2,
  IHTIYAC_KREDISI = 3,
  TASIT_KREDISI = 4,
  KONUT_KREDISI = 5,
  KARSILIKSIZ_CEK = 6,
  NAKDE_DONEN_TEMINAT_MEKTUBU = 7,
  NAKDE_DONEN_PREFINANSMAN_KREDI = 8,
  NAKDE_DONEN_AKREDITIF_TAAHHUDU = 9,
  NAKDE_DONEN_ITHALAT_KABUL_KRD_ = 10,
  NAKDE_DONEN_DIGER_GAYRINAKDI_KRD_ = 11,
  CEK = 12,
  TEMINAT_MEKTUBU = 13,
  AKREDITIF_KREDISI = 14,
  PREFINANSMAN_KREDISI = 15,
  KABUL_KREDISI = 16,
  HARICI_GARANTI = 17,
  DBS = 18,
  TUREV = 19,
  DIGER_GAYRINAKDI_KREDI = 20,
  TEB_KART = 21,
  ATM_HATALARI = 22,
  BUSINESS_KART = 23,
  CHARGEBACK_BEDELLERI = 24,
  DIGER_ALACAK = 25,
  GAYRINAKDI_KREDI = 26,
  POS_BEDELLERI = 27,
  PREFINANSMAN_KREDI = 28,
  TICARI_KREDI = 29,
  OKUL_KMFH = 30,
  TEMINAT_MEKTUBU_KOMISYONU = 31,
  HARICI_GARANTI_KOMISYONU = 32,
  KABUL_KRD_VE_AVAL_POLICE_KOMISYONU = 33,
  KONTRGARANTI_KOMISYONU = 34,
  AKREDITIF_KOMISYONU_UCRETI = 35,
  DIGER = 1031,
  DIGER2 = 1032,
  DIGER3 = 1033,
  DIGER4 = 1034,
  DIGER5 = 1035
}

export enum UrunTuru {
  KREDI_KARTLARI = 1,
  KMH = 2,
  KREDI = 3,
  NAKDE_DONEN_G_NAKDI_KREDILER = 4,
  G_NAKDILER = 5
}

export enum UrunTakipDurumu {
  YASAL_TAKIP = 1,
  ON_TAKIP = 2
}

export enum KGFTipi {
  OZ_KAYNAK = 1,
  HAZINE = 2
}

export enum UrunDurumu {
  ACIK = 1,
  KAPALI = 2
}
// kisa ack
export enum KambiyoSenediTipi {
  CEK = 1,
  SENET = 2,
  BONO = 3,
  POLICE = 4,
}
// uzun ack
export enum KambiyoSenediTipiAck {
  BONO_ACK = 3,
}

export enum LimitDurumu {
  LIMIT_IPOTEGI = 1,
  KARZ_ANAPARA_IPOTEGI = 2,
}

export enum IcraYenilemeDokumleri {
  ICRA_YENILEME_DILEKCESI = 1
}

export enum IcraYenilemeListeleri {
  ICRA_YENILEME_LISTESI = 1
}

export enum AboneIadeIstekDurum {
  OZETLEME_BASLADI = 1,
  OZETLEME_BITTI_DUSUM_BEKLIYOR = 2,
  MUNFERIT_IADE = 3,
  BASARILI = 4,
  IADE_FATURASI_BEKLENIYOR = 5,
  BASARILI_MUNFERIT = 6,
  BASARILI_IADE_FATURASI_GELDI = 7,
  HATALI = 8
}

export enum EtkiAnaliziDurum {
  BASLADI = 1,
  SONLANDI = 2
}

export enum AboneIadeIslemCevap {

}

export enum DosyaHariciAktarimIslemCevap {
  HOPE_ISLENEN_DOSYA_BASLANDI = 600,
  HOPE_ISLENEN_DOSYA_BASARILI = 601,
  HOPE_ISLENEN_DOSYA_HATALI = 602,
  HOPE_ISLENEN_DOSYA_BASLAMADI = 603
}

export enum BorcDusumTipi {
  BTK_KURUL_KARARI = 66623
}

export enum TaksitDurumu {
  DEVAM_EDIYOR = 1,
  IHLAL_EDILDI = 2,
  KAPANDI = 3,
  IPTAL_EDILDI = 4,
}

export enum TaksitRaporlari {
  TAKSIT_PLANI = 1,
  SOZLESME_DOKUMU = 2
}

export enum IcmalTahsilatTipi {
  ICRA_MUDURLUGU_TAHSILATI = 1,
  EMANET_DAGITILMAMIS = 2,
  EMANET_DAGITILMIS = 3,
  HUKUK_ONCESI_TAH_SEBEBI_ILE_DUSUM = 4
}

export enum Kurum {
  DIGER_BANKA = 2999,
  VERI_AKTARIM = 9999,
  SAP = 3509,
  TTS = 500,
  TMS = 3630,
  ATS_TT = 3700,
  ATS_TTNET = 3701,
  EASYDONE = 3730,
  UYAP = 3770,
  PTT = 2762,
  EFKS = 9571,
  TT_ADRES = 9580,
  ORKA = 3760,
  SAP_RMCA = 555,
  BPPS = 2555,
  FRAUD = 2601,
  BPM = 2706,
  EVO = 9582,
  MIND = 9583,
  YTS = 2716,
  EFYS = 3780,
  EDEVLET = 9000,
  OIM = 9001,
  RTDM = 9005,
  PAYFLEX = 3811,
  TTNET_KARA_GRI_LISTE_SISTEMI = 9587,
  THRONWEB = 9590,
  TEBIS = 9666

}

export enum Sorun {
  MASRAF_IPTAL_EDILMIS = 'MASRAF_IPTAL_EDILMIS',
  MASRAF_ONAY_GORMUS = 'MASRAF_ONAY_GORMUS',
  MASRAF_ICRA_ACIS = 'MASRAF_ICRA_ACIS',
  IPTAL_EDILEMEZ_EKLENMIS = 'IPTAL_EDILEMEZ_EKLENMIS',
  MASRAF_HACIZ_FEKKI = 'MASRAF_HACIZ_FEKKI',
  TAHSIL_EDILMIS_MASRAF = 'TAHSIL_EDILMIS_MASRAF',
  DUSUM_YAPILMIS_MASRAF = 'DUSUM_YAPILMIS_MASRAF',
  GERI_ALINMIS_MASRAF = 'GERI_ALINMIS_MASRAF',
  MASRAF_ISLEM_TARIHI_GECMIS = 'MASRAF_ISLEM_TARIHI_GECMIS',
  MASRAF_MASRAF_KAPAMA_TAL_EKLENMIS = 'MASRAF_MASRAF_KAPAMA_TAL_EKLENMIS',
  VEKIL_ONAYLANMIS_MASRAF_IPTAL_EDEMEZ = 'VEKIL_ONAYLANMIS_MASRAF_IPTAL_EDEMEZ',
  MASRAF_MASRAF_GERI_ALMA_TAL_EKLENMIS = 'MASRAF_MASRAF_GERI_ALMA_TAL_EKLENMIS',
  MASRAF_IPTAL_YETKISI_YOK = 'MASRAF_IPTAL_YETKISI_YOK',
  MASRAF_DOSYA_SISTEM_ASAMA_UYGUN_DEGIL = 'MASRAF_DOSYA_SISTEM_ASAMA_UYGUN_DEGIL',
  MASRAF_DOSYA_ASAMA_UYGUN_DEGIL = 'MASRAF_DOSYA_ASAMA_UYGUN_DEGIL',
  MASRAF_MERCI_ASAMA_UYGUN_DEGIL = 'MASRAF_MERCI_ASAMA_UYGUN_DEGIL',
  MASRAF_DURUM_ASAMA_UYGUN_DEGIL = 'MASRAF_DURUM_ASAMA_UYGUN_DEGIL',
  MASRAF_ICRA_HARICEN_YUKLENEN_MASRAF_SILME = 'MASRAF_ICRA_HARICEN_YUKLENEN_MASRAF_SILME',
  MASRAF_DAVA_HARICEN_YUKLENEN_MASRAF_SILME = 'MASRAF_DAVA_HARICEN_YUKLENEN_MASRAF_SILME',
  BILGISI_EKSIK = 'BILGISI_EKSIK',
  ASAMASI_UYGUN_DEGIL = 'ASAMASI_UYGUN_DEGIL',
  BILGI_HATASI = 'BILGI_HATASI',
  DURUMU_UYGUN_DEGIL = 'DURUMU_UYGUN_DEGIL',
  KONUSU_MUKERRER = 'KONUSU_MUKERRER',
  ICRA_DOSYA_NUMARASI_MUKERRER = 'ICRA_DOSYA_NUMARASI_MUKERRER',
  KILITLI = 'KILITLI',
  LIMITALTI = 'LIMITALTI',
  YENI_HAREKET_VAR = 'YENI_HAREKET_VAR',
  IPTAL_SURESI_GECTI = 'IPTAL_SURESI_GECTI',
  ALEYHTE_UYGUN_DEGIL = 'ALEYHTE_UYGUN_DEGIL',
  LEHTE_UYGUN_DEGIL = 'LEHTE_UYGUN_DEGIL',
  HABERLESME_UYGUN_DEGIL = 'HABERLESME_UYGUN_DEGIL',
  HASAR_UYGUN_DEGIL = 'HASAR_UYGUN_DEGIL',
  ILAMLI_UYGUN_DEGIL = 'ILAMLI_UYGUN_DEGIL',
  ILAMSIZ_UYGUN_DEGIL = 'ILAMSIZ_UYGUN_DEGIL',
  DAGITIMA_ESAS_TARIHI_GELMEMIS = 'DAGITIMA_ESAS_TARIHI_GELMEMIS',
  TAHSILAT_YAPILMIS = 'TAHSILAT_YAPILMIS',
  DOSYA_YONU_UYGUN_DEGIL = 'DOSYA_YONU_UYGUN_DEGIL',
  TAKIP_SEBEBI_UYGUN_DEGIL = 'TAKIP_SEBEBI_UYGUN_DEGIL',
  ILAM_DURUMU_UYGUN_DEGIL = 'ILAM_DURUMU_UYGUN_DEGIL',
  GERCEK_BORCLU_YOK = 'GERCEK_BORCLU_YOK',
  TUZEL_BORCLU_YOK = 'TUZEL_BORCLU_YOK',
  ICRA_DOSYA_NUMARASI_GIRILMIS = 'ICRA_DOSYA_NUMARASI_GIRILMIS',
  BAKIYESI_YETERSIZ = 'BAKIYESI_YETERSIZ',
  VERISI_BOZUK = 'VERISI_BOZUK',
  TERKIN = 'TERKIN',
  DOSYA_ASAMA_DOKUM_TIPI = 'DOSYA_ASAMA_DOKUM_TIPI',
  BORCLU_ASAMA_DOKUM_TIPI = 'BORCLU_ASAMA_DOKUM_TIPI',
  MAX_DOKUM_SAYISI = 'MAX_DOKUM_SAYISI',
  FINANSAL_HAREKET_ODEME_BILDIRIM = 'FINANSAL_HAREKET_ODEME_BILDIRIM',
  FINANSAL_HAREKET_IADE_BILDIRIM = 'FINANSAL_HAREKET_IADE_BILDIRIM',
  FINANSAL_HAREKET_BORC_DUSUM = 'FINANSAL_HAREKET_BORC_DUSUM',
  FINANSAL_HAREKET_TERKIN = 'FINANSAL_HAREKET_TERKIN',
  FINANSAL_HAREKET_VAR = 'FINANSAL_HAREKET_VAR',
  ODENMIS_MASRAF_VAR = 'ODENMIS_MASRAF_VAR',
  ADRES_EKSIK = 'ADRES_EKSIK',
  DOSYANIN_HASAR_FESIH_TARIHI_ESKI = 'DOSYANIN_HASAR_FESIH_TARIHI_ESKI',
  BORCLU_VEFAT_ETMIS = 'BORCLU_VEFAT_ETMIS',
  KAMPANYADAN_FAYDALANDIRILMIS = 'KAMPANYADAN_FAYDALANDIRILMIS',
  DOSYA_BAKIYESIZ_KALMIS = 'DOSYA_BAKIYESIZ_KALMIS',
  DOSYA_HITAM = 'DOSYA_HITAM',
  DOSYA_VEKILDE_DEGIL = 'DOSYA_VEKILDE_DEGIL',
  BAKIYEDE_SADECE_VU_VAR = 'BAKIYEDE_SADECE_VU_VAR',
  BAKIYE_VUDEN_AZ = 'BAKIYE_VUDEN_AZ',
  ACIK_MASRAF_VAR = 'ACIK_MASRAF_VAR',
  ACIK_DAVA_MASRAFI_VAR = 'ACIK_DAVA_MASRAFI_VAR',
  TCKN_DOGRULANMAMIS = 'TCKN_DOGRULANMAMIS',
  DOSYA_TERKIN = 'DOSYA_TERKIN',
  DOSYA_VEFATLI = 'DOSYA_VEFATLI',
  DOSYA_KILITLI = 'DOSYA_KILITLI',
  DOSYA_ABONELIK = 'DOSYA_ABONELIK',
  DOSYA_DIGER = 'DOSYA_DIGER',
  DOSYA_ICRA_ACILMAMIS = 'DOSYA_ICRA_ACILMAMIS',
  DOSYA_ICRA_ACILMIS = 'DOSYA_ICRA_ACILMIS',
  DOSYA_TEHIRI_ICRA = 'DOSYA_TEHIRI_ICRA',
  DOSYA_TEHIRI_ICRA_DEGIL = 'DOSYA_TEHIRI_ICRA_DEGIL',
  DOSYA_DOGITIM_TARIHIA = 'DOSYA_DOGITIM_TARIHIA',
  DOSYA_HUKUK_BAKIS_ACISI = 'DOSYA_HUKUK_BAKIS_ACISI',
  DOSYA_VEKIL_BAKIS_ACISI = 'DOSYA_VEKIL_BAKIS_ACISI',
  DOSYA_SORUMLULUGUNUZDA_DEGIL = 'DOSYA_SORUMLULUGUNUZDA_DEGIL',
  DOSYA_TALIMAT_SEBEBI_ILE_ERISTINIZ = 'DOSYA_TALIMAT_SEBEBI_ILE_ERISTINIZ',
  DOSYA_BIRINCI_EL = 'DOSYA_BIRINCI_EL',
  DOSYA_IKINCI_EL = 'DOSYA_IKINCI_EL',
  HUKUK_BA_VEKIL_DOSYALARI = 'HUKUK_BA_VEKIL_DOSYALARI',
  TOPLAM_MASAF_TUTAR = 'TOPLAM_MASAF_TUTAR',
  SUPHELI_ALACAK_DUZELTME_TUTAR = 'SUPHELI_ALACAK_DUZELTME_TUTAR',
  SUPHELI_ALACAK_BAKIYE_TUTAR = 'SUPHELI_ALACAK_BAKIYE_TUTAR',
  DOSYA_TAKSIT_VAR = 'DOSYA_TAKSIT_VAR',
  OTO_DOS_AKTARIM_IDARI_TAKIBE_ALINAMAZ = 'OTO_DOS_AKTARIM_IDARI_TAKIBE_ALINAMAZ',
  MANUEL_DOS_OLUSTURMA_IDARI_TAKIBE_ALINAMAZ = 'MANUEL_DOS_OLUSTURMA_IDARI_TAKIBE_ALINAMAZ',
  TAKIP_BASLATILMIS = 'TAKIP_BASLATILMIS',
  DOSYA_SISTEM_ASAMA_ATAMA_BEKLIYOR_GIRIS_TAMAMLANDI_DEGIL = 'DOSYA_SISTEM_ASAMA_ATAMA_BEKLIYOR_GIRIS_TAMAMLANDI_DEGIL',
  SUPHELI_ALACAK_TUTARI_IDRTKP_ALT_LIMITTEN_DUSUK = 'SUPHELI_ALACAK_TUTARI_IDRTKP_ALT_LIMITTEN_DUSUK',
  SUPHELI_ALACAK_TUTARI_IDRTKP_UST_LIMITTEN_YUKSEK = 'SUPHELI_ALACAK_TUTARI_IDRTKP_UST_LIMITTEN_YUKSEK',
  DAVAYA_BAGLI_ILAMLI_ICRA = 'DAVAYA_BAGLI_ILAMLI_ICRA',
  DOSYA_DURUMU_DERDEST_DEGIL = 'DOSYA_DURUMU_DERDEST_DEGIL',
  DOSYA_SISTEM_ASAMASI_IDARI_TAKIPTE_DEGIL = 'DOSYA_SISTEM_ASAMASI_IDARI_TAKIPTE_DEGIL',
  ODEME_SOZU_UZATMA_SURESI_DOLMADI = 'ODEME_SOZU_UZATMA_SURESI_DOLMADI',
  IDARI_TAKIPTE_KALMA_SURESI_DOLMADI = 'IDARI_TAKIPTE_KALMA_SURESI_DOLMADI',
  FATURASI_OLMAYAN_ABONELIK_DOSYASI = 'FATURASI_OLMAYAN_ABONELIK_DOSYASI',
  MASRAF_TUTARI_LIMIT_DISINDA = 'MASRAF_TUTARI_LIMIT_DISINDA',
  TOPLAM_MASRAF_ADEDI_UYGUN_DEGIL = 'TOPLAM_MASRAF_ADEDI_UYGUN_DEGIL',
  MASRAF_BEKLEME_SURESI_UYGUN_DEGIL = 'MASRAF_BEKLEME_SURESI_UYGUN_DEGIL',
  DOSYADA_UCRET_KALEM_YOK = 'DOSYADA_UCRET_KALEM_YOK',
  DOSYA_MASRAF_EKLENEMEZ = 'DOSYA_MASRAF_EKLENEMEZ',
  DOSYA_LIMIT_ALTI = 'DOSYA_LIMIT_ALTI',
  HARICI_TAHSIL_HARCI_MARAFI_EKLENEMEZ = 'HARICI_TAHSIL_HARCI_MARAFI_EKLENEMEZ',
  OTO_IDRTKP_CIKARMAYA_ENGEL_SON_FATURA_ODEME_TARIHLI_DOSYA = 'OTO_IDRTKP_CIKARMAYA_ENGEL_SON_FATURA_ODEME_TARIHLI_DOSYA',
  DOSYANIN_KISMI_TAHSILATI_VAR = 'DOSYANIN_KISMI_TAHSILATI_VAR',
  IDRTKP_ODEME_SOZU_TUTULDU_MU_HAYIR_DEGIL = 'IDRTKP_ODEME_SOZU_TUTULDU_MU_HAYIR_DEGIL',
  FINANS_ONAYI_YOK_TAKIP_BASLATILAMAZ = 'FINANS_ONAYI_YOK_TAKIP_BASLATILAMAZ',
  TAKIP_BASLAMADAN_MERCI_DOLU = 'TAKIP_BASLAMADAN_MERCI_DOLU',
  TAKIP_BASLAMADAN_ADLIYE_DOLU = 'TAKIP_BASLAMADAN_ADLIYE_DOLU',
  TAKIP_BASLAMADAN_MERCI_NO_DOLU = 'TAKIP_BASLAMADAN_MERCI_NO_DOLU',
  TAKIP_BASLAMADAN_ICRA_ACILDI_MI_EVET = 'TAKIP_BASLAMADAN_ICRA_ACILDI_MI_EVET',
  TAKIP_BASLAMADAN_HACIZ_TARIHI_DOLU = 'TAKIP_BASLAMADAN_HACIZ_TARIHI_DOLU',
  TAKIP_BASLAMADAN_SATIS_TARIHI_DOLU = 'TAKIP_BASLAMADAN_SATIS_TARIHI_DOLU',
  DOSYA_ASKIDA = 'DOSYA_ASKIDA',
  DOSYA_ASKIDA_DEGIL = 'DOSYA_ASKIDA_DEGIL',
  ATAMA_BEKLIYOR_DEGIL = 'ATAMA_BEKLIYOR_DEGIL',
  DOSYA_YONU_LEHE_DEGIL = 'DOSYA_YONU_LEHE_DEGIL',
  IDARI_TAKIP_VEKILI_DOLU = 'IDARI_TAKIP_VEKILI_DOLU',
  TAKSITLI_DOSYAYA_TAKIP_BASLATILAMAZ = 'TAKSITLI_DOSYAYA_TAKIP_BASLATILAMAZ',
  TAKIP_BASLATILMAMIS = 'TAKIP_BASLATILMAMIS',
  ATAMA_BEKLIYOR_DEGIL_TMD = 'ATAMA_BEKLIYOR_DEGIL_TMD',
  BIRINCI_EL = 'BIRINCI_EL',
  YETERLI_FAZLA_TAHSILAT_YOK = 'YETERLI_FAZLA_TAHSILAT_YOK',
  BAKIYE_LIMIT_ALTINA_AKTARIM_DEGERINDEN_BUYUK = 'BAKIYE_LIMIT_ALTINA_AKTARIM_DEGERINDEN_BUYUK',
  DOSYADA_BORCLU_VAR = 'DOSYADA_BORCLU_VAR',
  DOSYADA_BORCLU_YOK = 'DOSYADA_BORCLU_YOK',
  IDARI_TAKIPTEN_CIKIS_ALT_UST_LIMIT_UYGUN_DEGIL = 'IDARI_TAKIPTEN_CIKIS_ALT_UST_LIMIT_UYGUN_DEGIL',
  DOSYAYA_HTH_EKLENEMEZ = 'DOSYAYA_HTH_EKLENEMEZ',
  IKAZ_MEKTUBU_YOK = 'IKAZ_MEKTUBU_YOK',
  IKAZ_MEKTUBU_TEBLIG_SURE_BEKLENIYOR = 'IKAZ_MEKTUBU_TEBLIG_SURE_BEKLENIYOR',
  IKAZ_MEKTUBU_TEBLIG_EDILMEMIS = 'IKAZ_MEKTUBU_TEBLIG_EDILMEMIS',
  IKAZ_MEKTUBU_TEBLIG_TARIHI_BOS = 'IKAZ_MEKTUBU_TEBLIG_TARIHI_BOS',
  DOSYADA_MERCI_VE_MERCI_DOSYA_NO_BOS = "DOSYADA_MERCI_VE_MERCI_DOSYA_NO_BOS",
  DOSYADA_TAKSIT_VAR_MASRAF_EKLENEMEZ = 'DOSYADA_TAKSIT_VAR_MASRAF_EKLENEMEZ',
  IHTIYATI_HACIZ_DURUMU_UYGUN_DEGIL = 'IHTIYATI_HACIZ_DURUMU_UYGUN_DEGIL',
  UYAP_ILE_GELMIS_EKLENEMEZ = 'UYAP_ILE_GELMIS_EKLENEMEZ',
  DOSYA_ANAPARA_TUTARI_IDRTKP_ALT_LIMITTEN_DUSUK = 'DOSYA_ANAPARA_TUTARI_IDRTKP_ALT_LIMITTEN_DUSUK',
  KLASORE_BAGLI_DOSYA_VAR = 'KLASORE_BAGLI_DOSYA_VAR',
  DEVIR_HAREKETI_VAR = 'DEVIR_HAREKETI_VAR',
  UST_DOSYA_FIT_VAR = 'UST_DOSYA_FIT_VAR',
  OTO_IDARI_TAKIPTEN_CIKARILMIS = 'OTO_IDARI_TAKIPTEN_CIKARILMIS',
  DOSYA_FIT_VAR = 'DOSYA_FIT_VAR',
  DOSYA_ODEME_SOZU_VAR = 'DOSYA_ODEME_SOZU_VAR'
}

export enum HariciDosyaAktarimFileTypes {
  ZIP = 'application/zip, application/octet-stream, application/x-zip-compressed, multipart/x-zip',
  EXCEL = '.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel'
}

export enum MedeniDurum {
  EVLI = 1,
  BEKAR = 2,
  DUL = 3,
  BOSANMIS = 4
}

export enum MerciTipi {
  MAHKEME = 1,
  ICRA_MUDURLUGU = 2,
  SAVCILIK = 3
}

export enum HttpStatus {
  OK = 200, // Success
  BAD_REQUEST = 400, // ServiceException, HukukServiceException
  UNAUTHORIZED = 401, // ServiceException, HukukServiceException
  ACCESS_DENIED = 403, // AccessDeniedException
  INTERNAL_SERVER_ERROR = 500, // Throwable
  FOUND = 302, // Found, redirection
  NO_DATA_FOUND = 204
}

export enum KapamaTipi {
  TAHKAP = 1,
  DUSKAP = 2,
  KTAHKA = 3,
  TAHSILATSIZ = 4,
  IDARI_KARARLA = 5,
  FRAUD = 6,
  GECICI_ASKIYA_ALINAN = 7,
  HATALI_ISLEM = 8,
  UST_YONETIM_ONAYI = 9,
  TAHSILATLA_TAKIP_ONCESI = 10,
  HACZE_KABIL_MAL_YOK = 11,
  ITIRAZIN_IPTALI_DAVASI_SONUCUNDA = 12,
  VEFAT = 13,
  ITIRAZIN_IPTALI_DAVASI_ACILMAYAN = 14,
  ICRA_AFFI_ILE_KAPATILAN_DOSYALAR = 15
}

export enum SapDosyaSahibi {
  MUSTERI = 1,
  SATICI = 2
}

export enum BaglanmaSebebi {
  DAVBIR = 1,
  DAVAYR = 2,
  ILGI_DAVA = 4,
  DEVAM = 5,
  DEVAMI = 6,
  ILGI_DEGISIK_IS = 7,
  ILGI_ICRA = 8,
  ALTIC = 9,
  ALTDAV = 10,
  ALTDEG = 11
}

export enum DosyanoDegisimSebebi {
  VRAKTR = 1,
  HATGNC = 2,
  ICRAYN = 3,
  ICACBG = 4,
  DVACBG = 5,
  TEMSNC = 6,
  TARSNO = 7,
  GRVMHS = 8,
  YTKMHS = 9,
  IYTITR = 10,
  UYAP = 11,
  ISTGON = 12,
  TSMHS = 376
}

export enum KampanyaDurum {
  DVMEDI = 0,
  IHLAL = 1,
  SONERD = 2,
  FAYBEK = 3,
  FAYIPT = 4,
  IPTAL = 5
}

export enum FaturaDurum {
  ILK_GIRIS = 1,
  GUNCELLENDI = 2,
  IPTAL_EDILDI = 3,
  GUNCELLEME_GERI_ALINDI = 4,
  IPTAL_GERI_ALINDI = 5
}

export enum ReferansBilgiDurum {
  KULLANILMADI = 0,
  KULLANILDI = 1,
  GECERSIZ = 2,
  KULLANILDI_IPTAL_EDILECEK = 3,
  KULLANILDI_IPTAL_EDILDI = 4
}

export enum IslemKaynagi {
  GISE = 0,
  TTS_HUKUK_E_IADE = 39,
  VEKIL = 41,
  UYAP = 53
}

export enum DokumSistemOzel {
  SISTEM_DOKUMU = 0,
  OZEL_DOKUM = 1
}

export enum FinansalHareketIptal {
  IPTAL_EDILEBILIR = 1,
  IPTAL_TALEP_EDILEBILIR = 2
}

export enum TahsilatIptalTalep {
  HATALI_GIRIS = 1,
  DIGER = 2
}

export enum FaizIdirimTaksitSorun {
  DOSYA_TEMINATLI = 1,
  ORAN_ASILDI = 2,
  TARIH_ASILDI = 3,
  DOSYADA_IPOTEK_EMRI_VAR = 4,
  DOSYA_KGF_LI = 5,
  KONKORDATOLU_KISI_VAR = 6,
  TAKSIT_SINIRI_ASILDI = 7
}

export enum KullaniciTipi {
  KURUM_ICI_KULLANICI = 1,
  VEKIL = 6,
  GISE = 29
}

export enum UyapDosyaOlusturmaDurumu {
  ILK_GIRIS = 1,
  ORGANIZASYON_ONAYI_BEKLIYOR = 2,
  DOSYA_OLUSTURULMAYACAK = 3,
  HATALI_ORGANIZASYON = 4,
  DOSYA_OLUSTUR = 5,
  DOSYA_OLUSTURULDU = 6,
  ESLESME_YAPILDI = 7
}

export enum TakipBaslatmaTipi {
  MTS = 1,
  ICRA_MUDURLUGU = 2
}

export enum TebligSorguTipi {
  TUMU = 0,
  TEBLIGAT_CEVABI_BEKLEYENLER = 1,
  TAKIP_KESINLESTIRME_BEKLEYENLER = 2,
  ADRES_GIRISI_BEKLEYENLER = 3
}

export enum ItirazTutarDurumu {
  BORCUN_TAMAMINA_ITIRAZ = 1,
  BORCA_KISMI_ITIRAZ = 2
}

export enum AleyheOdemeAlacakliTipi {
  KISI = 1,
  KARSI_TARAF_VEKILI = 2,
  ICRA_MUDURLUGU = 3
}

export enum KonuGSM {
  FATURA_NO = 1,
  KONU_GSM = 2
}

export enum HatirlatmaTipi {
  KISISEL_HATIRLATMA = 0
}

export enum GoreliZaman {
  UC_GUN_ONCE = -4320
}

export enum AktarimListeleri {
  HDA_TEMPLATE_EXCEL_FILE = 1,
  HDA_KODLU_BILGI_EXCEL_FILE = 2
}

export enum AktarimIslemCevap {
  HDA_KAYDET_BASARILI = 4001,
  HDA_AKTARIM_BEKLIYOR = 4002,
  HDA_AKTARIM_BASLADI = 4003,
  HDA_AKTARIM_BASARILI = 4004,
  HDA_AKTARIM_BASARISIZ = 4005
}

export enum MutabakatDurumu {
  YAPILMADI = 1,
  OLUMLU = 2,
  OLUMSUZ = 3
}

export enum UygulamaTipi {
  DOSYA_GRUBU_BIRLESTIRME = 1,
  DOSYA_GRUBU_OLUSTURMA = 2,
  DOSYA_SORUN_DEGERLENDIRME = 3,
  FATURALAMA_BILGISI_OLUSTUR = 4,
  KAMPANYA_DAHIL_ET = 5,
  KAMPANYA_FAYDALANDIR = 6,
  KAMPANYA_SONLANDIR = 7,
  KUTUKTEN_TOPLU_DOSYA_GRUBU_OLUSTURMA = 8,
  BILDIRIM_EKLEME = 9,
  VEKIL_PERFORMANS_HESAPLA = 10,
  TOPLU_BORC_DUSUMU = 11,
  TOPLU_TERKIN = 12,
  HATIRLATMA_OLUSTUR = 13,
  DIS_SISTEM_VERI_DOSYASI_OLUSTUR = 14,
  MANUEL_BORDRO = 17,
  OTOMATIK_DOSYA_DAGITIM = 16,
  HESAP_BAZLI_BILDIRIM_OLUSTURMA = 18,
  ICRA_IADE_AL = 19,
  DAVA_IADE_AL = 20,
  ICRA_DEVRET = 21,
  DAVA_DEVRET = 22,
  ICRA_VEKILE_ATA = 23,
  DAVA_VEKILE_ATA = 24,
  ICRA_VEKIL_EKLE = 25,
  DAVA_VEKIL_EKLE = 26,
  VEKIL_HAM_VERI_HESAPLA = 27,
  TOPLU_BORDRO_HESAPLA = 28,
  VEKIL_PUAN_HESAPLA = 29,
  VEKIL_HAM_VERI_VE_PUAN_HESAPLA = 30,
  DOSYA_BIRLESTIRME_DATASI_HAZIRLA = 31,
  DOSYA_BIRLESTIRME_ATAMA = 32,
  UYAPTA_DOSYA_ARA = 34,
  MUALLAK_CACHE_GUNCELLEME = 35,
  UYAP_DOSYA_GRUBU_ANLIK_SORGULAMA = 36,
  VEKIL_DOSYA_SOZLESME_DEGISIKLIGI = 37,
  UYAP_DOSYA_GRUBU_DOGRULAMA_IPTALI = 38,
  UYAP_DOSYA_GRUBU_ESLESME_IPTALI = 39,
  DAVA_SIRKET_BIRIM_GUNCELLE = 40,
  PERIYODIK_MUALLAK_BILDIRIM = 41,
  HDA_ICRA_DOSYA_LISTESI = 42,
  HDA_DAVA_DOSYA_LISTESI = 43,
  HDA_ICRA_TUTAR_LISTESI = 44,
  HDA_DAVA_TUTAR_LISTESI = 45,
  IDARI_TAKIP_ATAMA_VERI_HAZIRLAMA = 46,
  HDA_TOPLU_EK_BILGI_TIPI_EKLEME = 53,
  HDA_TOPLU_DAVA_TURU_ALT_TURU_EKLEME = 54,
  HDA_TOPLU_ICRA_EK_BILGI_TIPI_EKLEME = 55,
  DOSYA_GRUBU_TOPLU_IKAZ_MEKTUBU_SILME = 57,
}

export enum EkranBilgiGuncelleTanim {
  VEKIL_GUNCELLEME_AYARLARI = 1,
  VEKIL_SIRKET_GUNCELLEME_AYARLARI = 2,
  DAVA_GORUS_PARAMETRELERI_AYARLARI = 3
}

export enum MKTEklenmeTipi {
  GIRIS_MASRAFLARINI_ODE = 1,
  TAHSIL_EDILMIS_MASRAFLARI_ODE = 2,
  MASRAF_ODENMEZ = 3,
}

export enum UyapDosyaTuru {
  ICRA_DOSYASI_HARIC_TUMU = 53,
  ICRA_DOSYASI = 35,
  TALIMAT_DOSYASI = 1,
  CEZA_DAVA_DOSYASI = 3,
  HUKUK_DAVA_DOSYASI = 15,
  IDARE_DAVA_DOSYASI = 9,
  BOLGE_DOSYASI = 10,
  YD_ITIRAZ_DOSYASI = 11,
  ORT_GID_SATIS_DOSYASI = 168,
  VERGI_DAVA_DOSYASI = 28,
  IFLAS_DOSYASI = 36,
  DAVA_SARTI_ARABULUCULUK_DOSYASI = 313,
  DAVA_SARTI_ARABULUCULUK_BASVURU_DOSYASI = 312,
  TEREKE_DOSYASI = 78,
  ADLI_TIP_DOSYASI = 22,
  HAKEM_DAVA_DOSYASI = 79,
  TEREKE_SATIS_DOSYASI = 255,
  KAMU_DOSYASI = 12,
  HUKUK_DEGISIK_IS_DOSYASI = 14,
  ICRA_IZALE_I_SUYU_DOSYASI = 73,
  VESAYET_SATIS_DOSYASI = 256,
  IHTIYARI_ARABULUCULUK_DOSYASI = 262,
  IHTIYARI_ARABULUCULUK_BASVURU_DOSYASI = 263,
  TICARI_DAVA_SARTI_ARABULUCULUK_BASVURU_DOSYASI = 330,
  TICARI_DAVA_SARTI_ARABULUCULUK_DOSYASI = 331,
  MTS = 294,
  HAKEM_KARARLARI_SAKLAMA_DOSYASI = 328,
  TUKETICI_DAVA_SARTI_ARABULUCULUK_BASVURU_DOSYASI = 358,
  TUKETICI_DAVA_SARTI_ARABULUCULUK_DOSYASI = 359,
}

export enum BildirimTipi {
  SMS_BILDIRIM = 1,
  EPOSTA_BILDIRIM = 2,
  FINANSAL_HAREKET_BILDIRIM = 3,
  SUPHELI_ALACAK_BILDIRIMI = 4,
  BAGIMSIZ_BOLUM_KODU = 5,
  BORDRO = 6,
  ICMAL_TAHSILAT = 7,
  TALEP = 8,
  ALEYHE_ODEME_TALEP = 9,
  BILDIRIM_HESAP_BAZLI = 10,
  DYS_BILDIRIM = 11,
  BILDIRIM_FATURA_KAPAMA = 12,
  BILDIRIM_MUHASEBE = 13,
  EDEVLET_ALACAK_IADE_BILDIRIMI = 14,
  IGB_KAPAMA_BILDIRIMI = 15,
  SAVCILIK_HAREKET = 16,
  PLAKADAN_ADRES_SORGULA = 17,
  BILDIRIM_MUALLAK = 18,
  DOSYA_KAPAMA_ACMA_BILDIRIMI = 19,
  ICRA_KAPAMA_ACMA_BILDIRIMI = 20,
  AVANS_FAIZ_BILDIRIMI = 21,
  CCB_BILDIRIMI = 22,
  BANKA_HAREKET_BILDIRIMI = 23,
  VEKIL_HAREKET_BILDIRIMI = 24,
  ABONE_IADE_BILDIRIMI = 25,
  MUSTERI_HESAP_OLUSTURMA_BILDIRIMI = 26,
  OTOYOL_EDEVLET_BILDIRIMI = 27,
  MANUEL_BILDIRIM = 32
}

export enum BildirimAltTipi {

  BANKA_HAREKET_TAHSILAT = 37,
  BANKA_HAREKET_TEMINAT = 38,
  BANKA_HAREKET_URUN_KAPAMA = 39,
  BANKA_HAREKET_MASRAF_ISLEM = 41,
  BILDIRIM_MANUEL_SMS = 56,
  BILDIRIM_MANUEL_EPOSTA = 57,
  BILDIRIM_MANUEL_POSTA = 58,
  BILDIRIM_MANUEL_DIGER = 59
}

export enum SistemAsamasiForHariciAktarimIcra {
  ATAMA_BEKLIYOR = 1,
  IDARI_TAKIPTE = 102,
}

export enum SistemAsamasiForHariciAktarimDava {
  ATAMA_BEKLIYOR = 1,
}


export enum KonfigurasyonParametreleriIslemTuru {
  CREATE = 'CREATE',
  DELETE = 'DELETE',
  UPDATE = 'UPDATE'
}


export enum MonthNames {
  OCAK = 1,
  SUBAT = 2,
  MART = 3,
  NISAN = 4,
  MAYIS = 5,
  HAZIRAN = 6,
  TEMMUZ = 7,
  AGUSTOS = 8,
  EYLUL = 9,
  EKIM = 10,
  KASIM = 11,
  ARALIK = 12
}


export enum ModeHolderType {
  GORUNTULE = 'goruntule',
  GUNCELLE = 'guncelle',
  YENIKAYIT = 'yenikayit'
}

export enum TakipTipiIdari {
  YASAL_TAKIPTE = 0,
  IDARI_TAKIPTE = 1
}

export enum DurumEvetHayir {
  AKTIF = 1, PASIF = 0
}

export enum NumberConstants {
  // @ts-ignore
  LONG_TYPE_MAX_SIZE = 9223372036854775807n,
}
